export const SITUATIONS = [
  {id:'cable-route',skill:'electric',resolver:'designer',title:'Куда вести кабель?',text:'На схеме лоток проходит сквозь балку. Электрик предлагает провести «как обычно», но обычно никто не помнит как.',choices:[{id:'reroute',title:'Обойти балку по проекту',deltas:{budget:-8,time:1,quality:2,trust:0}},{id:'direct',title:'Пусть делают как быстрее',deltas:{budget:0,time:0,quality:-3,trust:-1}}]},
  {id:'socket-height',skill:'electric',resolver:'supervision',title:'Розетки на какой отметке?',text:'В чертеже 300 мм, в ведомости 450 мм, у заказчика столы с кабель-каналом на 620.',choices:[{id:'verify',title:'Остановить и сверить мебель',deltas:{budget:-2,time:1,quality:3,trust:1}},{id:'average',title:'Сделать среднее арифметическое',deltas:{budget:0,time:0,quality:-4,trust:-2}}]},
  {id:'unknown-cable',skill:'electric',resolver:'supervision',title:'Чей это кабель?',text:'Нашли живую линию без маркировки. Отключить страшно, оставить ещё страшнее, позвонить владельцу некому.',choices:[{id:'trace',title:'Трассировать и оформить',deltas:{budget:-7,time:1,quality:3,trust:0}},{id:'wall',title:'Аккуратно зашить обратно',deltas:{budget:0,time:0,quality:-3,trust:-2}}]},
  {id:'primer',skill:'paint',resolver:'supervision',title:'Грунтовать второй раз?',text:'Стена впитывает краску с энтузиазмом бюджета. Маляры спрашивают, считать ли это основанием для допработ.',choices:[{id:'prime',title:'Грунтовать и сфотографировать',deltas:{budget:-6,time:1,quality:3,trust:0}},{id:'paint',title:'Краски не жалеть',deltas:{budget:-3,time:0,quality:-2,trust:0}}]},
  {id:'ral',skill:'paint',resolver:'designer',title:'Какой из двух RAL настоящий?',text:'На банке один номер, в ведомости другой. Архитектор говорит «тот, который теплее», прибор молчит.',choices:[{id:'sample',title:'Сделать выкрас и согласовать',deltas:{budget:-3,time:1,quality:2,trust:2}},{id:'can',title:'Верить банке',deltas:{budget:0,time:0,quality:-2,trust:-2}}]},
  {id:'wet-wall',skill:'paint',resolver:'supervision',title:'Стена ещё влажная',text:'Маляр готов продолжать, потому что график сухой. Стена с графиком не согласна.',choices:[{id:'dry',title:'Дать высохнуть',deltas:{budget:0,time:2,quality:4,trust:0}},{id:'continue',title:'Закрыть следующим слоем',deltas:{budget:0,time:0,quality:-5,trust:-1}}]},
  {id:'server-box',skill:'moving',resolver:'pm',title:'Это можно отключать?',text:'Перестановщики держат коробку с проводами. IT утверждает, что это «критическая инфраструктура», но приехать не может.',choices:[{id:'wait-it',title:'Вызвать IT и ждать',deltas:{budget:-2,time:1,quality:1,trust:2}},{id:'move',title:'Сфотографировать и перенести',deltas:{budget:0,time:0,quality:-1,trust:-3}}]},
  {id:'lift',skill:'moving',resolver:'pm',title:'Грузовой лифт занят',text:'На следующие два часа лифт забронировали соседи. Их диван имеет больший административный ресурс.',choices:[{id:'swap',title:'Обменять слот через УК',deltas:{budget:-4,time:0,quality:0,trust:1}},{id:'stairs',title:'Нести по лестнице',deltas:{budget:-6,time:1,quality:-1,trust:0}}]},
  {id:'lost-box',skill:'moving',resolver:'procurement',title:'Коробка без адреса',text:'На ней написано «важное». Таких коробок уже семь, а важных помещений — девять.',choices:[{id:'inventory',title:'Открыть и занести в ведомость',deltas:{budget:0,time:1,quality:2,trust:1}},{id:'meeting',title:'Отнести в переговорную',deltas:{budget:0,time:0,quality:-1,trust:-1}}]},
  {id:'missing-fasteners',skill:'furniture',resolver:'procurement',title:'Не хватает крепежа',text:'Сборщики уверяют, что завод положил ровно столько, сколько считал нужным. Завод недоступен.',choices:[{id:'local',title:'Купить локальный аналог',deltas:{budget:-5,time:0,quality:0,trust:1}},{id:'borrow',title:'Разобрать один готовый стол',deltas:{budget:0,time:0,quality:-2,trust:-1}}]},
  {id:'left-right',skill:'furniture',resolver:'designer',title:'Левая тумба или правая?',text:'План мебели зеркальный относительно плана электрики. Оба выпущены «в производство».',choices:[{id:'coordinate',title:'Сверить розетки и пересобрать',deltas:{budget:-4,time:1,quality:3,trust:1}},{id:'alternate',title:'Чередовать для ритма',deltas:{budget:0,time:0,quality:-3,trust:-2}}]},
  {id:'chair-sample',skill:'furniture',resolver:'procurement',title:'Кресло не того цвета',text:'Поставщик называет оттенок «уголь». Заказчик называет его «грязный синий».',choices:[{id:'replace',title:'Зафиксировать замену партии',deltas:{budget:-8,time:2,quality:2,trust:2}},{id:'lighting',title:'Объяснить особенностью света',deltas:{budget:0,time:0,quality:-1,trust:-2}}]},
  {id:'hidden-act',skill:'documentation',resolver:'doc-control',title:'Кто подпишет скрытые работы?',text:'Работа уже скрыта, акт ещё открыт, ответственный подрядчика символически в отпуске.',choices:[{id:'open',title:'Вскрыть участок и оформить',deltas:{budget:-9,time:1,quality:3,trust:1}},{id:'retro',title:'Собрать подписи задним числом',deltas:{budget:0,time:0,quality:-4,trust:-3}}]},
  {id:'passport',skill:'documentation',resolver:'doc-control',title:'Паспорт на материал не совпадает',text:'Название почти то же, производитель почти тот, документ почти настоящий.',choices:[{id:'replace-doc',title:'Запросить корректный комплект',deltas:{budget:-1,time:1,quality:2,trust:1}},{id:'file',title:'Подшить как есть',deltas:{budget:0,time:0,quality:-3,trust:-2}}]},
  {id:'scheme',skill:'documentation',resolver:'doc-control',title:'Исполнительная схема не исполнительная',text:'На ней показано, как хотели сделать. Люди на площадке помнят, как сделали, но по-разному.',choices:[{id:'measure',title:'Перемерить и перечертить',deltas:{budget:-5,time:1,quality:4,trust:1}},{id:'stamp',title:'Поставить штамп на проект',deltas:{budget:0,time:0,quality:-5,trust:-2}}]},
  {id:'column',skill:'design',resolver:'designer',title:'Колонна не там',text:'По факту колонна смещена на 180 мм. По проекту она ведёт себя безупречно.',choices:[{id:'revise',title:'Перевыпустить узел',deltas:{budget:-4,time:1,quality:3,trust:1}},{id:'trim',title:'Подрезать мебель на месте',deltas:{budget:-7,time:0,quality:-2,trust:-1}}]},
  {id:'door-swing',skill:'design',resolver:'designer',title:'Двери встречаются',text:'Две двери открываются навстречу и создают переговорную комнату на одного очень худого человека.',choices:[{id:'redraw',title:'Изменить открывание',deltas:{budget:-3,time:1,quality:3,trust:1}},{id:'closer',title:'Поставить доводчики помедленнее',deltas:{budget:-2,time:0,quality:-3,trust:-1}}]},
  {id:'ceiling',skill:'design',resolver:'designer',title:'Светильник попал в решётку',text:'Архитектор, вентиляция и свет независимо выбрали центр помещения.',choices:[{id:'coordinate',title:'Развести потолочный план',deltas:{budget:-3,time:1,quality:3,trust:1}},{id:'shift',title:'Сдвинуть то, что легче',deltas:{budget:-1,time:0,quality:-2,trust:0}}]},
  {id:'dust',skill:'cleaning',resolver:'pm',title:'Можно уже убирать?',text:'Клининг приехал вовремя, то есть раньше окончания всех остальных работ.',choices:[{id:'zone',title:'Закрывать зоны поэтапно',deltas:{budget:-3,time:0,quality:2,trust:1}},{id:'all',title:'Убрать всё один раз сейчас',deltas:{budget:0,time:0,quality:-3,trust:-1}}]},
  {id:'protection',skill:'cleaning',resolver:'supervision',title:'Снимать защитную плёнку?',text:'Под плёнкой чисто. Над плёнкой продолжают пилить. Заказчик идёт через час.',choices:[{id:'route',title:'Снять только маршрут показа',deltas:{budget:-2,time:0,quality:1,trust:2}},{id:'all',title:'Снять всю — должно же быть красиво',deltas:{budget:0,time:0,quality:-3,trust:0}}]},
  {id:'access',skill:'management',resolver:'pm',title:'У кого ключ от помещения?',text:'Все ответственные на месте. Ключ тоже на месте, но на другом ответственном.',choices:[{id:'master',title:'Оформить мастер-ключ',deltas:{budget:-2,time:1,quality:1,trust:1}},{id:'door',title:'Попросить открыть «аккуратно»',deltas:{budget:-3,time:0,quality:-2,trust:-1}}]},
  {id:'change-order',skill:'management',resolver:'pm',title:'Это дополнительная работа?',text:'Подрядчик говорит «не было в объёме». Смета говорит мало, переписка говорит слишком много.',choices:[{id:'protocol',title:'Разобрать объём и оформить',deltas:{budget:-4,time:1,quality:1,trust:2}},{id:'pressure',title:'Сказать, что всё было очевидно',deltas:{budget:0,time:0,quality:-1,trust:-3}}]},
  {id:'substitution',skill:'management',resolver:'procurement',title:'Материал закончился',text:'Поставщик предлагает «полный аналог», у которого совпадает только назначение.',choices:[{id:'approve',title:'Проверить образец и согласовать',deltas:{budget:-3,time:1,quality:2,trust:1}},{id:'take',title:'Брать, пока есть',deltas:{budget:0,time:0,quality:-3,trust:-2}}]},
  {id:'inspection-point',skill:'management',resolver:'supervision',title:'Звать заказчика сейчас?',text:'Узел готов к освидетельствованию. Через два часа его закроют, через три заказчик сможет приехать.',choices:[{id:'delay',title:'Подождать и показать',deltas:{budget:-2,time:2,quality:3,trust:2}},{id:'photo',title:'Закрыть по фотографиям',deltas:{budget:0,time:0,quality:-2,trust:-1}}]},
];

export const situationById=new Map(SITUATIONS.map(item=>[item.id,item]));

