import test from'node:test';
import assert from'node:assert/strict';
import{FITOUT_CAST_IDS,FITOUT_CAST_STORIES,characterLines,ContextualDialogueDirector}from'../prototypes/lib/fitout-cast-stories.js';
import{FitoutRun}from'../prototypes/lib/fitout-run.js';

test('every living cast member has a biography, six relationships and at least fifty authored lines',()=>{assert.equal(FITOUT_CAST_IDS.length,7);for(const id of FITOUT_CAST_IDS){const story=FITOUT_CAST_STORIES[id];assert.ok(story.biography.length>120,id);assert.equal(Object.keys(story.relationships).length,6,id);assert.ok(characterLines(id).length>=50,id);assert.equal(new Set(characterLines(id)).size,characterLines(id).length,id)}});

test('dialogue selection follows work, problem, pressure and nearby person context without random choice',()=>{const director=new ContextualDialogueDirector(),moving=director.next('vera',{state:'to_supply',order:{id:'cable-1',phase:'engineering',kind:'socket'}}),blocked=director.next('vera',{state:'to_work',blocked:true}),mistake=director.next('vera',{mistake:'hidden_socket'}),pressure=director.next('vera',{pressure:90}),relationship=director.next('vera',{otherId:'boris',relationshipMoment:true});assert.equal(moving.context,'moving');assert.equal(blocked.context,'blocked');assert.equal(mistake.context,'mistake');assert.equal(pressure.context,'pressure');assert.equal(relationship.context,'relationship');assert.match(relationship.text,/Борис/);const repeatableA=new ContextualDialogueDirector().next('semyon',{event:'arrival'}),repeatableB=new ContextualDialogueDirector().next('semyon',{event:'arrival'});assert.deepEqual(repeatableA,repeatableB)});

test('a fitout run is seeded, escalates modifiers and preserves lessons outside the run',()=>{const first=new FitoutRun({seed:'office-17',depth:3}),second=new FitoutRun({seed:'office-17',depth:3});assert.deepEqual(first.snapshot().modifiers,second.snapshot().modifiers);assert.equal(first.modifiers.length,2);first.start();first.tick(12);first.remember('vera',4,'перенесли розетку');first.finish({won:false,mistakes:['socket_hidden']});assert.equal(first.status,'lost');assert.equal(first.meta.relationships.vera,4);assert.ok(first.meta.lessons.includes('socket_hidden'));const next=new FitoutRun({seed:'office-18',depth:4,meta:first.meta});assert.equal(next.relationship('vera'),4);assert.equal(next.meta.runs,1)});
