import test from'node:test';
import assert from'node:assert/strict';
import*as THREE from'three';
import{generateCharacter,frameRect,anchoredFrameDestination}from'../prototypes/lib/character-generator.js';
import{ANIMATION_MANIFEST,APPEARANCE_PACKS,availablePresentations,validateAnimationManifest,validateCharacterDefinition,makeCharacterDefinition}from'../prototypes/lib/character-appearance.js';
import{GameState}from'../prototypes/lib/gameplay-systems.js';
import{ContextActions}from'../prototypes/lib/context-actions.js';
import{createCrate}from'../prototypes/lib/construction-assets.js';
import{CHARACTER_CLASSES,workCapability,eligibleWork}from'../prototypes/lib/character-classes.js';
import{NavigationGrid}from'../prototypes/lib/navigation-grid.js';
import{CharacterBrain,createScreenDirectionResolver,contextReady}from'../prototypes/lib/character-ai.js';
import{generateBiography,BIOGRAPHY_VARIANT_FLOOR}from'../prototypes/lib/character-biographies.js';
import{generateBark,commandDialogue,reportsTo,DIALOGUE_VARIANT_FLOOR}from'../prototypes/lib/character-dialogues.js';
import{generateSite,advanceRoom,generateSpatialTasks,generateSpatialEvent,validateSite}from'../prototypes/lib/spatial-generator.js';

test('prototype character generator reproduces a worker from one seed',()=>{const a=generateCharacter('crew-42'),b=generateCharacter('crew-42'),c=generateCharacter('crew-43');assert.deepEqual(a,b);assert.notEqual(a.id,c.id);assert.match(a.name,/\s/);assert.equal(a.traits.length,2)});

test('procedural biographies are deterministic, gendered and numerous',()=>{const woman=generateCharacter('bio-woman',{role:'electrician',appearance:{packId:'drafted_electrician_female_v1'}}),man=generateCharacter('bio-man',{role:'foreman'});assert.deepEqual(woman.biography,generateBiography('bio-woman','electrician','feminine'));assert.match(woman.biography.summary,/Она /);assert.match(man.biography.summary,/Он /);assert.ok(BIOGRAPHY_VARIANT_FLOOR>10000);const unique=new Set(Array.from({length:500},(_,index)=>generateBiography(`person-${index}`,'foreman','masculine').summary));assert.ok(unique.size>300)});

test('character class and appearance are separate deterministic contracts',()=>{const vera=generateCharacter('vera-electrician',{role:'electrician',name:'Вера Искрова',appearance:{packId:'drafted_electrician_female_v1'}}),generatedWoman=generateCharacter('female-electrician',{role:'electrician',appearance:{packId:'drafted_electrician_female_v1'}}),architect=generateCharacter('architect',{role:'architect'}),client=generateCharacter('client',{role:'client'});assert.equal(vera.role,'electrician');assert.equal(APPEARANCE_PACKS[vera.appearance.packId].genderPresentation,'feminine');assert.match(generatedWoman.name,/а\s.+а$/);assert.equal(architect.appearance.packId,'drafted_architect_v1');assert.equal(client.appearance.packId,'drafted_client_v1');assert.equal(validateAnimationManifest(ANIMATION_MANIFEST).ok,true);assert.equal(validateCharacterDefinition(makeCharacterDefinition(vera),{classes:{electrician:{}}}).ok,true)});

test('sprite frames keep their feet anchor instead of crawling sideways',()=>{const rect={width:100,height:120},target={x:10,y:20,width:200,height:240},left=anchoredFrameDestination(rect,{centerX:42,bottom:113},target),right=anchoredFrameDestination(rect,{centerX:58,bottom:113},target);assert.equal(left.x,26);assert.equal(right.x,-6);assert.equal(left.y,right.y)});

test('npc direction is resolved in camera space like the player direction',()=>{const resolve=createScreenDirectionResolver({x:-.6,z:.8},{x:-.8,z:-.6});assert.equal(resolve(-.8,-.6),'right');assert.equal(resolve(.8,.6),'left');assert.equal(resolve(.6,-.8),'front');assert.equal(resolve(-.6,.8),'back')});

test('character atlas exposes eight walk frames and four work frames',()=>{const profile=generateCharacter('eight-frames',{role:'foreman'}),walk=new Set(),work=new Set();for(let time=0;time<1.2;time+=.14)walk.add(frameRect('walk','front',time,1600,800,profile).frame);for(let time=0;time<1;time+=.22)work.add(frameRect('drill','front',time,1024,1536,profile).frame);assert.equal(profile.animation.frames.walk,8);assert.equal(walk.size,8);assert.equal(work.size,4);assert.equal(frameRect('idle','back',0,1200,1200,profile).height,300)});

test('character classes forbid absurd autonomous work and preserve trade identity',()=>{assert.equal(workCapability('architect','drill_wall').allowed,false);assert.equal(workCapability('electrician','install_socket').efficiency,1);assert.equal(workCapability('worker','drill_wall').efficiency,.58);assert.equal(workCapability('architect','drill_wall',{allowOffProfile:true}).efficiency,.24);const points=[{workId:'drawings'},{workId:'paint_wall'},{workId:'smoke'}];assert.deepEqual(eligibleWork('architect',points).map(item=>item.workId),['drawings','smoke'])});

test('project party roles expose distinct verbs instead of one universal worker',()=>{assert.equal(workCapability('project_manager','plan_project').allowed,true);assert.equal(workCapability('client','request_change').allowed,true);assert.equal(workCapability('designer','drawings').allowed,true);assert.equal(workCapability('plumber','install_pipes').allowed,true);assert.equal(workCapability('inspector','inspect_work').allowed,true);assert.equal(workCapability('client','carry_materials').allowed,false);assert.equal(workCapability('inspector','install_socket').allowed,false)});

test('designer and architect are separate visible classes',()=>{assert.equal(CHARACTER_CLASSES.designer.label,'Проектировщик');assert.equal(CHARACTER_CLASSES.architect.label,'Архитектор');assert.equal(workCapability('designer','drawings').efficiency,1);assert.equal(workCapability('architect','concept_design').efficiency,1);assert.equal(workCapability('designer','concept_design').efficiency,.58)});

test('designer architect GIP GAP and inspector have distinct classes and silhouettes',()=>{const designer=generateCharacter('designer-role',{role:'designer'}),architect=generateCharacter('architect-role',{role:'architect'}),gip=generateCharacter('gip-role',{role:'gip'}),gap=generateCharacter('gap-role',{role:'gap'}),inspector=generateCharacter('inspector-role',{role:'inspector'});assert.equal(designer.appearance.packId,'drafted_designer_male_v1');assert.equal(architect.appearance.packId,'drafted_architect_v1');assert.equal(gip.appearance.packId,'drafted_gip_v1');assert.equal(gap.appearance.packId,'drafted_gap_v1');assert.equal(inspector.appearance.packId,'drafted_inspector_v1');assert.equal(workCapability('gip','coordinate_design').efficiency,1);assert.equal(workCapability('gap','approve_architecture').efficiency,1)});

test('helmet color communicates trade while accent customizes clothing',()=>{const foreman=generateCharacter('white-helmet',{role:'foreman'}),electrician=generateCharacter('blue-helmet',{role:'electrician',appearance:{packId:'drafted_electrician_female_v1',accentTone:'#c45783'}});assert.equal(foreman.appearance.packId,'drafted_foreman_white_v1');assert.equal(foreman.appearance.helmetTone,'#f4f5ef');assert.equal(electrician.appearance.helmetTone,'#2878c7');assert.equal(electrician.appearance.accentTone,'#c45783');assert.notEqual(electrician.appearance.helmetTone,electrician.appearance.accentTone)});

test('available gender presentation follows real asset packs instead of profession logic',()=>{assert.deepEqual(availablePresentations('worker'),['masculine']);assert.deepEqual(availablePresentations('electrician'),['masculine','feminine']);const beard=generateCharacter('worker-a',{role:'worker'}),clean=generateCharacter('worker-b',{role:'worker'});assert.ok(['drafted_builder_v1','drafted_worker_clean_v1'].includes(beard.appearance.packId));assert.ok(['drafted_builder_v1','drafted_worker_clean_v1'].includes(clean.appearance.packId));assert.equal(generateCharacter('boss',{role:'project_manager'}).appearance.packId,'drafted_project_manager_v1')});

test('navigation grid routes around a blocked wall and returns reachable targets',()=>{const grid=new NavigationGrid({minX:0,maxX:4,minZ:0,maxZ:4,cellSize:1,blocked:[{x:2,z:1.5,width:1,depth:3,padding:0}]});const path=grid.findPath({x:0,z:0},{x:4,z:0});assert.ok(path.length>5);assert.equal(path.some(point=>point.x===2&&point.z<=3),false);assert.equal(grid.reachable({x:0,z:0},[{x:4,z:0}]).length,1)});

test('bot brain selects only work allowed to its class and follows the generated path',()=>{const grid=new NavigationGrid({minX:0,maxX:4,minZ:0,maxZ:4,cellSize:.5}),profile=generateCharacter('architect-bot',{role:'architect'}),actor={position:{x:0,y:0,z:0},direction:'front'},points=[{id:'wall',workId:'drill_wall',position:{x:1,z:0},station:{kind:'wall',object:{visible:true}}},{id:'desk',workId:'drawings',position:{x:3,z:0},duration:1,station:{kind:'desk',object:{visible:true}}}],brain=new CharacterBrain({profile,actor,navigation:grid,workPoints:points});assert.equal(brain.target.workId,'drawings');for(let i=0;i<300;i++)brain.update(1/60);assert.notEqual(brain.target?.workId,'drill_wall')});

test('work animation requires a real visible station of the right type',()=>{assert.equal(contextReady({workId:'assemble_panel'}),false);assert.equal(contextReady({workId:'assemble_panel',station:{kind:'desk',object:{visible:true}}}),false);assert.equal(contextReady({workId:'assemble_panel',station:{kind:'panel',object:{visible:false}}}),false);assert.equal(contextReady({workId:'assemble_panel',station:{kind:'panel',object:{visible:true}}}),true)});

test('space generator creates valid mutable rooms tasks and contextual events',()=>{const site=generateSite('floor-a',{stage:'demolition'}),same=generateSite('floor-a',{stage:'demolition'});assert.deepEqual(site,same);assert.equal(validateSite(site).ok,true);assert.equal(site.rooms.length,6);const before=generateSpatialTasks(site).length,room=site.rooms[1],previous=room.stage;advanceRoom(site,room.id);assert.notEqual(room.stage,previous);assert.equal(site.revision,2);assert.equal(generateSpatialTasks(site).length,before);const incident=generateSpatialEvent(site,'event-a');assert.ok(incident);assert.ok(site.rooms.some(item=>item.id===incident.roomId))});

test('generated speech follows class and field workers report through the foreman',()=>{const pm=generateCharacter('pm-dialogue',{role:'project_manager'}),foreman=generateCharacter('foreman-dialogue',{role:'foreman'}),worker=generateCharacter('worker-dialogue',{role:'worker',supervisorId:foreman.id}),bark=generateBark(worker,{state:'carry',index:4}),toForeman=commandDialogue({speaker:pm,target:foreman,seed:'direct-order'}),toWorker=commandDialogue({speaker:pm,target:worker,seed:'field-order'});assert.equal(reportsTo('worker'),'foreman');assert.equal(reportsTo('foreman'),'project_manager');assert.equal(worker.reporting.supervisorId,foreman.id);assert.equal(toForeman.outcome,'accepted');assert.ok(['accepted','redirected','refused'].includes(toWorker.outcome));if(toWorker.outcome==='redirected')assert.equal(toWorker.routedToId,foreman.id);assert.match(bark.speaker,/\s/);assert.ok(DIALOGUE_VARIANT_FLOOR>60)});

test('verified tape advances the quest and modifies surveying only while equipped',()=>{const game=new GameState('chapter-test'),base=game.skills.surveying;game.startQuest('measure_opening');game.emit('talked','semyon');assert.equal(game.quests.get('measure_opening').objectives[1].id,'tape');game.addItem('verified_tape');assert.equal(game.skills.surveying,base);assert.equal(game.skillValue('surveying'),base);assert.equal(game.equip('verified_tape'),true);assert.equal(game.skillValue('surveying'),base+28);game.emit('measured','doorway');assert.equal(game.quests.get('measure_opening').state,'complete');assert.equal(game.xp,45);assert.equal(game.skillPoints,1)});

test('door procurement spends cash, rejects the wrong size and advances only a correct order',()=>{const game=new GameState('door-order');game.startQuest('order_door');game.emit('supply_opened','door');const wrong=game.placeDoorOrder(800,2000);assert.equal(wrong.correct,false);assert.equal(game.economy.cash,161000);assert.equal(game.quests.get('order_door').current,1);const correct=game.placeDoorOrder(910,2110);assert.equal(correct.correct,true);assert.equal(game.economy.cash,103000);assert.equal(game.economy.spent,77000);assert.equal(game.quests.get('order_door').current,2);game.installDoor();game.toggleDoor(true);assert.equal(game.quests.get('order_door').state,'complete');assert.equal(game.project.door.open,true)});

test('skill development spends one point and changes the base skill',()=>{const game=new GameState('skills');game.skillPoints=1;const before=game.skills.communication;assert.equal(game.upgradeSkill('communication'),true);assert.equal(game.skills.communication,before+5);assert.equal(game.skillPoints,0);assert.equal(game.upgradeSkill('communication'),false)});

test('context manager selects only the nearest enabled action',()=>{const actor={position:new THREE.Vector3()},prompt={classList:{toggle(){}},innerHTML:''},manager=new ContextActions({actor,promptElement:prompt});let fired='';manager.register({id:'far',object:{position:new THREE.Vector3(1.2,0,0)},label:'far',action:()=>{fired='far'}});manager.register({id:'near',object:{position:new THREE.Vector3(.6,0,0)},label:'near',action:()=>{fired='near'}});manager.register({id:'disabled',object:{position:new THREE.Vector3(.1,0,0)},label:'disabled',enabled:()=>false,action:()=>{fired='disabled'}});assert.equal(manager.update().id,'near');assert.equal(manager.trigger(),true);assert.equal(fired,'near')});

test('construction crate opens over time and its quest item can be removed',()=>{const crate=createCrate();assert.equal(crate.target,0);crate.open();for(let i=0;i<30;i++)crate.update(1/60);assert.ok(crate.progress>.9);assert.equal(crate.contents.visible,true);crate.takeContents();crate.update(1/60);assert.equal(crate.contents.visible,false)});
