import test from'node:test';
import assert from'node:assert/strict';
import{SiteWorkBoard,SiteWorkerBrain}from'../prototypes/lib/site-workforce.js';

test('physical work cannot progress without a claimed worker at the task',()=>{const board=new SiteWorkBoard({orders:[{id:'wall-1',phase:'partition',roles:['worker'],duration:2,target:{x:2,z:0},pickup:{x:0,z:0}}]});board.enablePhase('partition');assert.equal(board.phaseProgress('partition'),0);assert.equal(board.work('boris','wall-1',1).ok,false);assert.equal(board.phaseProgress('partition'),0);const order=board.claim('boris',['worker']);assert.equal(order.id,'wall-1');assert.equal(board.work('boris','wall-1',1).ok,false);assert.equal(board.begin('boris','wall-1'),true);board.work('boris','wall-1',1);assert.equal(board.phaseProgress('partition'),.5)});

test('worker walks to supply, carries material, walks to the cell, and completes it',()=>{const board=new SiteWorkBoard({orders:[{id:'socket-1',phase:'engineering',roles:['electrician'],duration:.3,target:{x:2,z:0},pickup:{x:1,z:0}}]});board.enablePhase('engineering');const actor={position:{x:0,z:0},direction:'front'},navigation={findPath:(from,to)=>[{x:from.x,z:from.z},{x:to.x,z:to.z}]},states=[],brain=new SiteWorkerBrain({workerId:'vera',roles:['electrician'],actor,board,navigation,speed:4,move:(subject,delta)=>{subject.position.x+=delta.x;subject.position.z+=delta.z;return{moved:Math.hypot(delta.x,delta.z)}},onStateChange:state=>states.push(state)});for(let index=0;index<180&&!board.phaseComplete('engineering');index++)brain.tick(1/60);assert.equal(board.phaseComplete('engineering'),true);assert.ok(states.includes('to_supply'));assert.ok(states.includes('carrying'));assert.ok(states.includes('to_work'));assert.ok(states.includes('working'));assert.ok(actor.position.x>1.7)});

test('priority focus changes which matching cell is claimed first',()=>{const board=new SiteWorkBoard({orders:[{id:'near',phase:'finish',roles:['worker'],target:{x:0,z:0}},{id:'far',phase:'finish',roles:['worker'],target:{x:8,z:0},priority:3}]});board.enablePhase('finish');board.setFocus({x:0,z:0});assert.equal(board.claim('boris',['worker']).id,'near')});

test('pausing a phase releases its people and freezes progress',()=>{const board=new SiteWorkBoard({orders:[{id:'desk',phase:'furniture',roles:['worker'],duration:1,target:{x:0,z:0}}]});board.enablePhase('furniture');board.claim('boris',['worker']);board.begin('boris','desk');board.work('boris','desk',.25);board.pausePhase('furniture');assert.equal(board.order('desk').status,'queued');assert.equal(board.activeFor('boris'),null);assert.equal(board.work('boris','desk',.5).ok,false);assert.equal(board.phaseProgress('furniture'),.25)});
