import{createSeededRng}from'./character-generator.js';
import{eligibleWork,workCapability,WORK_TYPES,CHARACTER_CLASSES}from'./character-classes.js';

export function contextReady(point){const required=WORK_TYPES[point?.workId]?.station;if(!required)return true;return point?.station?.kind===required&&point.station.object?.visible!==false}

export class CharacterBrain{
  constructor({profile,actor,navigation,workPoints,seed=profile.seed,directionResolver=resolveWorldDirection}){this.profile=profile;this.actor=actor;this.navigation=navigation;this.workPoints=workPoints;this.rng=createSeededRng(`${seed}:brain`);this.directionResolver=directionResolver;this.state='idle';this.target=null;this.path=[];this.pathIndex=0;this.stateTime=0;this.workTime=0;this.moveSpeed=0;this.onStateChange=null;this.chooseNext()}
  setState(state,target=null){if(this.state===state&&this.target===target)return;this.state=state;this.target=target;this.stateTime=0;this.onStateChange?.(state,target)}
  chooseNext(){const actorClass=this.profile.role,available=eligibleWork(actorClass,this.workPoints.filter(point=>point.enabled!==false&&contextReady(point)&&!['rest','smoke'].includes(point.workId))),classRules=CHARACTER_CLASSES[actorClass],disciplineShift=(this.profile.stats.discipline-65)/500,shouldWork=this.rng()<Math.max(.25,Math.min(.98,(classRules?.workBias??.7)+disciplineShift));let target;if(shouldWork&&available.length)target=available[Math.floor(this.rng()*available.length)];else{const breaks=this.workPoints.filter(point=>['rest','smoke'].includes(point.workId)&&contextReady(point));target=breaks[Math.floor(this.rng()*breaks.length)]||available[0]}if(!target){this.setState('idle');this.workTime=1.5;return}const path=this.navigation.findPath(this.actor.position,target.position);if(path.length<2){this.beginWork(target);return}this.target=target;this.path=path;this.pathIndex=1;this.setState('walk',target)}
  beginWork(target){if(!contextReady(target)){this.setState('idle');this.workTime=1;return}const capability=workCapability(this.profile.role,target.workId);this.target=target;this.workTime=(target.duration||4)/Math.max(.25,capability.efficiency);this.setState(WORK_TYPES[target.workId]?.animation||'idle',target)}
  update(dt){this.stateTime+=dt;if(this.state==='walk'){const waypoint=this.path[this.pathIndex];if(!waypoint){this.moveSpeed=0;this.beginWork(this.target);return}const dx=waypoint.x-this.actor.position.x,dz=waypoint.z-this.actor.position.z,distance=Math.hypot(dx,dz);if(distance<.08){this.pathIndex++;return}const targetSpeed=1.25+this.profile.stats.discipline/100;this.moveSpeed=smoothLerp(this.moveSpeed,targetSpeed,1-Math.exp(-dt*8));const step=Math.min(distance,dt*this.moveSpeed);this.actor.position.x+=dx/distance*step;this.actor.position.z+=dz/distance*step;this.actor.direction=this.directionResolver(dx,dz);return}this.moveSpeed=0;this.workTime-=dt;if(this.workTime<=0)this.chooseNext()}
}
const smoothLerp=(from,to,amount)=>from+(to-from)*amount;
export function resolveWorldDirection(dx,dz){return Math.abs(dx)>Math.abs(dz)?(dx>0?'right':'left'):(dz>0?'front':'back')}
export function createScreenDirectionResolver(forward,right){return(dx,dz)=>{const screenX=dx*right.x+dz*right.z,screenY=dx*forward.x+dz*forward.z;return Math.abs(screenX)>Math.abs(screenY)?(screenX>0?'right':'left'):(screenY<0?'front':'back')}}
