import{createSeededRng,pickSeeded}from'./seed-utils.js';

export const FITOUT_RUN_SECONDS=180;
export const FITOUT_DESIGN_SECONDS=40;
export const FITOUT_BUILD_SECONDS=110;
export const FITOUT_COMMISSION_SECONDS=30;

export const RUN_MODIFIERS={
  narrow_delivery:{id:'narrow_delivery',label:'Узкий грузовой вход',effect:'Длинные материалы переносятся медленнее.',carryRate:.78,pressure:4},
  legacy_wiring:{id:'legacy_wiring',label:'Наследство прежнего арендатора',effect:'Часть электрических трасс обнаруживается только после разметки.',engineeringRate:.82,pressure:6},
  live_office:{id:'live_office',label:'Работающий этаж',effect:'Шумные работы приходится чередовать с тихими.',workRate:.86,pressure:7},
  late_change:{id:'late_change',label:'Новая хотелка заказчика',effect:'После первого фронта появляется изменение планировки.',workRate:.92,pressure:8},
  missing_lift:{id:'missing_lift',label:'Лифт снова занят',effect:'Поставки приходят рывками.',carryRate:.7,pressure:5},
  fixed_opening:{id:'fixed_opening',label:'Неподвижный вход',effect:'Вход нельзя переносить, весь офис обязан подстроиться.',workRate:1,pressure:3},
  cost_pressure:{id:'cost_pressure',label:'Бюджет уже оптимизировали',effect:'Переделка сильнее бьёт по итоговой оценке.',workRate:.95,pressure:9}
};

export class FitoutRun{
  constructor({seed='fitout-run',depth=1,meta={},duration=FITOUT_RUN_SECONDS,designDuration=FITOUT_DESIGN_SECONDS,buildDuration=FITOUT_BUILD_SECONDS,commissionDuration=FITOUT_COMMISSION_SECONDS,modifierIds=[]}={}){this.seed=String(seed);this.depth=Math.max(1,Number(depth)||1);this.duration=Math.max(1,Number(duration)||FITOUT_RUN_SECONDS);this.designDuration=Math.min(this.duration,Math.max(1,Number(designDuration)||FITOUT_DESIGN_SECONDS));this.buildDuration=Math.min(this.duration,Math.max(1,Number(buildDuration)||FITOUT_BUILD_SECONDS));this.commissionDuration=Math.min(this.duration,Math.max(1,Number(commissionDuration)||FITOUT_COMMISSION_SECONDS));this.elapsed=0;this.planningElapsed=0;this.buildingElapsed=0;this.commissioningElapsed=0;this.status='planning';this.quality=100;this.budget=100;this.decisions=[];this.events=[];this.meta={runs:0,wins:0,relationships:{},lessons:[],lastOutcome:null,...meta};const rng=createSeededRng(`${this.seed}:${this.depth}`),pool=Object.values(RUN_MODIFIERS),count=Math.min(pool.length,1+Math.floor((this.depth-1)/2));this.modifiers=[...new Set(modifierIds)].map(id=>RUN_MODIFIERS[id]).filter(Boolean);while(this.modifiers.length<count){const modifier=pickSeeded(rng,pool);if(!this.modifiers.includes(modifier))this.modifiers.push(modifier)}this.pressure=this.modifiers.reduce((sum,item)=>sum+item.pressure,0)}
  start(){if(this.status!=='planning')return false;this.status='building';this.events.push({type:'run_started',at:this.elapsed,modifiers:this.modifiers.map(item=>item.id)});return true}
  tickPlanning(dt){if(this.status!=='planning')return this.status;const step=Math.max(0,Number(dt)||0);this.planningElapsed=Math.min(this.designDuration,this.planningElapsed+step);this.elapsed=Math.min(this.duration,this.elapsed+step);return this.status}
  tick(dt){if(this.status!=='building')return this.status;const step=Math.max(0,Number(dt)||0);this.buildingElapsed=Math.min(this.buildDuration,this.buildingElapsed+step);this.elapsed=Math.min(this.duration,this.elapsed+step);if(this.remaining<=0)this.finish({won:false,mistakes:['deadline']});return this.status}
  startCommissioning(){if(this.status!=='building')return false;this.status='commissioning';this.events.push({type:'commissioning_started',at:this.elapsed});return true}
  tickCommissioning(dt){if(this.status!=='commissioning')return this.status;const step=Math.max(0,Number(dt)||0);this.commissioningElapsed=Math.min(this.commissionDuration,this.commissioningElapsed+step);this.elapsed=Math.min(this.duration,this.elapsed+step);return this.status}
  decide(id,choice){if(this.status!=='building'||this.decisions.some(item=>item.id===id))return false;const safe=choice==='fix',decision={id:String(id),choice:safe?'fix':'risk',at:this.elapsed};if(safe){const delay=5;this.buildingElapsed=Math.min(this.buildDuration,this.buildingElapsed+delay);this.elapsed=Math.min(this.duration,this.elapsed+delay);this.budget=Math.max(0,this.budget-4);decision.delay=delay;decision.budget=-4}else{this.quality=Math.max(0,this.quality-12);this.budget=Math.max(0,this.budget-1);decision.quality=-12;decision.budget=-1}this.decisions.push(decision);this.events.push({type:'decision',...decision});if(this.remaining<=0)this.finish({won:false,mistakes:['deadline']});return decision}
  get remaining(){const phaseRemaining=this.status==='planning'?this.designDuration-this.planningElapsed:this.status==='commissioning'?this.commissionDuration-this.commissioningElapsed:this.buildDuration-this.buildingElapsed;return Math.max(0,Math.min(this.duration-this.elapsed,phaseRemaining))}
  relationship(id){return Number(this.meta.relationships[id])||0}
  remember(id,amount,reason){this.meta.relationships[id]=Math.max(-100,Math.min(100,this.relationship(id)+amount));this.events.push({type:'relationship',id,amount,reason,at:this.elapsed});return this.meta.relationships[id]}
  finish({won=false,mistakes=[]}={}){if(!['building','planning','commissioning'].includes(this.status))return false;this.status=won?'won':'lost';this.meta.runs=(this.meta.runs||0)+1;if(won)this.meta.wins=(this.meta.wins||0)+1;this.meta.lastOutcome={won,seed:this.seed,depth:this.depth,mistakes:[...mistakes],quality:this.quality,budget:this.budget,seconds:Math.round(this.elapsed)};for(const mistake of mistakes)if(!this.meta.lessons.includes(mistake))this.meta.lessons.push(mistake);this.events.push({type:'run_finished',won,mistakes:[...mistakes],at:this.elapsed});return true}
  rate(kind){return this.modifiers.reduce((rate,item)=>rate*(kind==='carry'?(item.carryRate||1):kind==='engineering'?(item.engineeringRate||item.workRate||1):(item.workRate||1)),1)}
  snapshot(){return{seed:this.seed,depth:this.depth,duration:this.duration,designDuration:this.designDuration,buildDuration:this.buildDuration,commissionDuration:this.commissionDuration,elapsed:this.elapsed,planningElapsed:this.planningElapsed,buildingElapsed:this.buildingElapsed,commissioningElapsed:this.commissioningElapsed,remaining:this.remaining,status:this.status,quality:this.quality,budget:this.budget,pressure:this.pressure,decisions:this.decisions.map(item=>({...item})),modifiers:this.modifiers.map(item=>({...item})),meta:JSON.parse(JSON.stringify(this.meta)),events:this.events.map(item=>({...item}))}}
}
