import{createSeededRng}from'./seed-utils.js';
import{generateSite,generateSpatialTasks,generateSpatialEvent,advanceRoom,setRoomStage}from'./spatial-generator.js';
import{generateCharacter}from'./character-generator.js';
import{commandDialogue}from'./character-dialogues.js';

export const SANDBOX_TASK_RULES={
  survey:{roles:['foreman','project_manager'],duration:18,cost:8,quality:4,label:'Обследовать помещение'},
  demolish:{roles:['worker','foreman'],duration:24,cost:18,quality:-1,label:'Выполнить демонтаж'},
  build_partitions:{roles:['foreman','worker'],duration:28,cost:24,quality:1,label:'Собрать перегородки'},
  install_engineering:{roles:['electrician','gip'],duration:32,cost:36,quality:2,label:'Смонтировать инженерию'},
  finish_surfaces:{roles:['finisher'],duration:30,cost:29,quality:3,label:'Выполнить отделку'},
  install_furniture:{roles:['worker','foreman'],duration:22,cost:21,quality:1,label:'Расставить мебель'}
};

const PERSON_SPECS=[
  ['foreman','Семён Проёмов','foreman-main'],['worker','Борис Тихонов','helper-main'],['electrician','Вера Искрова','electrician-main'],
  ['finisher','Роман Ровный','finisher-main'],['gip','Ирина Коллизиева','gip-main'],['inspector','Аркадий Актов','inspector-main'],
  ['client','Анна Крылова','client-main']
];

const CHATTER={foreman:['Я всем поставил задачу. Теперь ищу всех.','Кто видел журнал работ? Только честно.','РП, на минуту. Минут на сорок.'],worker:['Я уберу. Сразу после того, как найду того, кто намусорил.','Проход был свободен утром. Это исторический факт.'],electrician:['Не трогайте кабель. Особенно мокрыми обещаниями.','Щит подписан. Почерк не мой.'],finisher:['Мы не красили. Мы делали образец на всей стене.','Поверхность готова почти полностью, кроме поверхности.'],gip:['Коллизия согласована устно с человеком без полномочий.','Сейчас выпущу схему. Старую пока никому не показывайте.'],inspector:['Я просто посмотрю. Это не угроза, это процедура.','Скрытые работы потому и скрытые, что вы их от меня скрыли.'],client:['Я заехала на пять минут. Почему все побледнели?','В презентации лужи были меньше.']};

export class MechanicsSandbox{
  constructor(seed='Полигон-01'){
    this.version=1;this.seed=String(seed);this.rng=createSeededRng(`${seed}:runtime`);this.site=generateSite(seed,{stage:'demolition'});['demolition','rough','engineering','finish','demolition','rough'].forEach((stage,index)=>setRoomStage(this.site,this.site.rooms[index].id,stage));this.player=generateCharacter(`${seed}:player`,{role:'project_manager',name:'Олег Черненко'});
    this.people=PERSON_SPECS.map(([role,name,suffix])=>generateCharacter(`${seed}:${suffix}`,{role,name}));const foreman=this.people.find(person=>person.role==='foreman');for(const person of this.people)if(person.reporting.supervisorRole==='foreman')person.reporting.supervisorId=foreman.id;
    this.day={duration:300,remaining:300,elapsed:0,paused:false,finished:false};this.economy={cash:420,earned:0,spent:0};this.quality=68;this.reputation=55;this.xp=0;this.accepted=0;this.changedRooms=new Set();this.tasks=new Map();this.log=[];this.chat=[];this.pendingEvent=null;this.nextEventAt=34;this.eventIndex=0;this.nextChatAt=6;this.nextClientInspectionAt=48;this.nextHazardDamageAt=18;this.magicReadyAt=0;this.status='playing';this.listeners=new Set();this.hazards=[{id:'trash-1',kind:'trash',roomId:this.site.rooms[4].id,status:'active',label:'Куча мусора',detail:'Обрезки ГКЛ обрели коллектив и требуют отдельный контейнер.'},{id:'cable-1',kind:'cable',roomId:this.site.rooms[2].id,status:'active',label:'Кабель под напряжением',detail:'Конец кабеля висит там, где у людей обычно проходят руки.'},{id:'puddle-1',kind:'puddle',roomId:this.site.rooms[2].id,status:'active',label:'Протечка',detail:'Сантехника закончилась внезапно, вода решила продолжить.'}];this.refreshCatastrophes();this.refreshTasks();this.note('Смена началась. На объекте уже есть проблемы, хотя договор ещё пахнет принтером.');this.chatMessage('Семён Проёмов','Доброе утро. Кто уже на объекте — не пугайтесь, это временно.');
  }
  subscribe(listener){this.listeners.add(listener);listener(this);return()=>this.listeners.delete(listener)}
  notify(){for(const listener of this.listeners)listener(this)}
  note(text,tone='normal'){this.log.unshift({time:this.day.elapsed,text,tone});this.log=this.log.slice(0,18)}
  chatMessage(sender,text,tone='normal'){this.chat.push({id:`chat-${this.chat.length+1}-${Math.floor(this.day.elapsed*10)}`,time:this.day.elapsed,sender,text,tone});this.chat=this.chat.slice(-80)}
  activeHazards(){return this.hazards.filter(item=>item.status!=='resolved')}
  hazard(id){return this.hazards.find(item=>item.id===id)}
  refreshCatastrophes(){const dangerousRooms=new Set(this.hazards.filter(item=>item.status!=='resolved'&&['cable','puddle'].includes(item.kind)).map(item=>item.roomId));for(const roomId of dangerousRooms){const kinds=new Set(this.hazards.filter(item=>item.roomId===roomId&&item.status!=='resolved').map(item=>item.kind)),existing=this.hazards.find(item=>item.kind==='electrified_puddle'&&item.roomId===roomId);if(kinds.has('cable')&&kinds.has('puddle')&&!existing)this.hazards.push({id:`catastrophe-${roomId}`,kind:'electrified_puddle',roomId,status:'active',label:'Лужа под напряжением',detail:'Электрика встретила сантехнику. Знакомство прошло с искрой.'});else if(existing&&(!kinds.has('cable')||!kinds.has('puddle')))existing.status='resolved'}}
  resolveHazard(id,method='chat'){const hazard=this.hazard(id);if(!hazard||hazard.status==='resolved')return{ok:false};if(method==='shout'){const chance=hazard.kind==='trash'?.72:hazard.kind==='electrified_puddle'?.18:.42,success=this.rng()<chance;this.chatMessage('Олег Черненко',hazard.kind==='trash'?'УБРАТЬ ЭТО НЕМЕДЛЕННО. И НЕ ПИШИТЕ, ЧТО УБРАЛИ — УБЕРИТЕ.':'КТО ОСТАВИЛ ЭТО В ТАКОМ ВИДЕ?!','player');if(success){hazard.status='resolved';this.xp+=4;this.note(`${hazard.label}: крик неожиданно материализовался в действие.`,'good')}else{this.reputation=Math.max(0,this.reputation-1);this.note(`${hazard.label}: крик услышали все. Исполнителя среди них не оказалось.`,'warning')}this.refreshCatastrophes();this.notify();return{ok:true,success}}hazard.status='assigned';hazard.resolveAt=this.day.elapsed+(hazard.kind==='trash'?13:hazard.kind==='electrified_puddle'?24:18);this.chatMessage('Олег Черненко',hazard.kind==='trash'?'Прораб, организовать уборку и фото сюда.':'Электрики и сантехники: оградить, обесточить и устранить. Семён контролирует.','player');this.note(`${hazard.label}: поручение ушло в чат. Галочки пока серые.`,'warning');this.notify();return{ok:true,success:true,delayed:true}}
  sendChatCommand(command){const match={cleanup:['trash'],deenergize:['cable','electrified_puddle'],foreman:['puddle','trash','cable','electrified_puddle']}[command]||[],hazard=this.activeHazards().find(item=>match.includes(item.kind));if(!hazard){this.chatMessage('Олег Черненко',command==='cleanup'?'Клининг, подтвердите отсутствие того, что я сейчас не вижу.':command==='deenergize'?'Электрики, подтвердите безопасность. Без слова «вроде».':'Семён, доложите обстановку. Коротко, но правду.','player');this.chatMessage('Семён Проёмов','Принял. Ищу предмет доклада.');this.notify();return{ok:true,empty:true}}return this.resolveHazard(hazard.id,'chat')}
  sendUrgent(taskId){const task=this.task(taskId)||[...this.tasks.values()].find(item=>item.status==='working');this.chatMessage('Олег Черненко','СДЕЛАТЬ СРОЧНО. Почему не готово? Срок был вчера.','player');if(!task||task.status!=='working'){this.chatMessage('Семён Проёмов','Какую именно работу? В чате уточняют все одновременно.');this.notify();return{ok:true,empty:true}}const success=this.rng()<.62;if(success){task.progress=Math.min(.96,task.progress+.12);this.chatMessage(this.person(task.assigneeId).name,'Принял. Ускоряемся. Обед официально переносится.','good')}else{this.reputation=Math.max(0,this.reputation-1);this.chatMessage(this.person(task.assigneeId).name,'Мы и так срочно. Теперь просто громче.','warning')}this.notify();return{ok:true,success,task}}
  refreshTasks(){for(const raw of generateSpatialTasks(this.site)){if(this.tasks.has(raw.id))continue;const rule=SANDBOX_TASK_RULES[raw.workType];if(!rule)continue;this.tasks.set(raw.id,{...raw,label:rule.label,status:'available',assigneeId:null,progress:0,duration:rule.duration,baseCost:rule.cost,qualityDelta:rule.quality,urgency:Math.round(45+this.rng()*50),deadline:this.day.elapsed+65+this.rng()*85})}}
  task(id){return this.tasks.get(id)}
  availableTasks(){return[...this.tasks.values()].filter(task=>['available','working','awaiting_acceptance'].includes(task.status))}
  person(id){return this.people.find(person=>person.id===id)}
  canPerform(person,task){return Boolean(person&&task&&SANDBOX_TASK_RULES[task.workType]?.roles.includes(person.role))}
  issueCommand(taskId,targetId,{throughSupervisor=false}={}){const task=this.task(taskId),target=this.person(targetId);if(!task||task.status!=='available')return{ok:false,reason:'task'};if(!this.canPerform(target,task))return{ok:false,reason:'profile',text:`${target?.roleLabel||'Исполнитель'} не умеет: ${task.label}.`};let dialogue={outcome:'accepted',accepted:true,response:'Принято.'};if(!throughSupervisor)dialogue=commandDialogue({speaker:this.player,target,command:task.label,urgency:task.urgency,seed:`${this.seed}:${task.id}:${target.id}:${Math.floor(this.day.elapsed)}`});if(!dialogue.accepted){this.note(`${target.name}: ${dialogue.response}`,'warning');this.notify();return{ok:false,reason:dialogue.outcome,dialogue}}const cost=task.baseCost;if(this.economy.cash<cost)return{ok:false,reason:'cash',text:'В кассе не хватает денег даже на уверенный кивок.'};this.economy.cash-=cost;this.economy.spent+=cost;task.status='working';task.assigneeId=target.id;task.throughSupervisor=throughSupervisor;this.note(`${target.name} начал: ${task.label} · ${task.roomLabel}.`);this.notify();return{ok:true,dialogue,task}}
  pauseTask(taskId){const task=this.task(taskId);if(!task||task.status!=='working')return false;task.status='available';task.assigneeId=null;this.note(`${task.label} остановлена. Бригада делает вид, что так и планировалось.`,'warning');this.notify();return true}
  tick(seconds){if(this.day.paused||this.pendingEvent||this.status!=='playing')return;seconds=Math.max(0,Math.min(.25,Number(seconds)||0));this.day.elapsed+=seconds;this.day.remaining=Math.max(0,this.day.duration-this.day.elapsed);for(const task of this.tasks.values()){if(task.status!=='working')continue;const person=this.person(task.assigneeId),speed=.72+(person.stats.competence/100)*.55+(task.throughSupervisor ? .12 : 0);task.progress=Math.min(1,task.progress+seconds*speed/task.duration);if(task.progress>=1){task.status='awaiting_acceptance';this.note(`${task.label} закончена. Пока только физически — нужна приёмка.`,'good');this.chatMessage(person.name,`${task.roomLabel}: закончили. Можно предъявлять, если смелые.`)}}for(const task of this.tasks.values())if(['available','working'].includes(task.status)&&this.day.elapsed>task.deadline&&!task.overdue){task.overdue=true;this.reputation=Math.max(0,this.reputation-3);this.note(`${task.roomLabel}: срок задачи истёк. Заказчик научился пользоваться часами.`,'danger')}for(const hazard of this.hazards.filter(item=>item.status==='assigned'&&this.day.elapsed>=item.resolveAt)){hazard.status='resolved';this.chatMessage('Семён Проёмов',`${hazard.label}: устранили. Фото приложил мысленно.`,'good');this.note(`${hazard.label}: бригада действительно устранила проблему.`,'good');this.refreshCatastrophes()}if(this.day.elapsed>=this.nextChatAt){const person=this.people[Math.floor(this.rng()*this.people.length)],lines=CHATTER[person.role]||['Есть вопрос. Пока формулируем последствия.'];this.chatMessage(person.name,lines[Math.floor(this.rng()*lines.length)]);this.nextChatAt=this.day.elapsed+7+this.rng()*8}if(this.day.elapsed>=this.nextClientInspectionAt){const hazard=this.activeHazards().find(item=>!item.clientSaw&&item.kind!=='electrified_puddle')||this.activeHazards().find(item=>!item.clientSaw);if(hazard){hazard.clientSaw=true;this.reputation=Math.max(0,this.reputation-5);this.chatMessage('Анна Крылова',`${hazard.label} — это тоже часть утверждённой концепции? Жду объяснение от РП.`,'client');this.note(`Заказчик первым обнаружил: ${hazard.label}. Отвечать теперь вам.`,'danger')}this.nextClientInspectionAt=this.day.elapsed+48+this.rng()*35}if(this.day.elapsed>=this.nextHazardDamageAt){const catastrophe=this.activeHazards().find(item=>item.kind==='electrified_puddle');if(catastrophe){this.quality=Math.max(0,this.quality-3);this.reputation=Math.max(0,this.reputation-2);this.chatMessage('Семён Проёмов','Оградили лужу стулом. Стул проводит совещание. Нужны электрики.','danger')}this.nextHazardDamageAt=this.day.elapsed+18}if(this.day.elapsed>=this.nextEventAt&&!this.pendingEvent){this.pendingEvent=generateSpatialEvent(this.site,`${this.seed}:sandbox-event:${this.eventIndex++}`);this.nextEventAt=this.day.elapsed+42+this.rng()*34;if(this.pendingEvent)this.note(`${this.pendingEvent.roomLabel}: ${this.pendingEvent.text}`,'danger')}if(this.day.remaining<=0)this.finishDay();this.checkOutcome();this.notify()}
  presentTask(taskId){const task=this.task(taskId);if(!task||task.status!=='awaiting_acceptance')return{ok:false};const assignee=this.person(task.assigneeId),chance=Math.min(.92,.48+assignee.stats.competence/240+this.quality/500),roll=this.rng();if(roll>chance){task.status='working';task.progress=.58;task.duration*=.72;this.quality=Math.max(0,this.quality-4);this.note(`${task.roomLabel}: технадзор не принял. Переделка — это прогресс, который пошёл обратно.`,'danger');this.notify();return{ok:true,accepted:false,roll,chance}}task.status='accepted';this.accepted++;this.xp+=25;this.quality=Math.min(100,this.quality+task.qualityDelta);const payment=34+Math.round(task.baseCost*.65);this.economy.cash+=payment;this.economy.earned+=payment;advanceRoom(this.site,task.roomId);this.changedRooms.add(task.roomId);this.note(`${task.roomLabel} принята. Заказчик заплатил ${payment} тыс. ₽ и временно доволен.`,'good');this.refreshTasks();this.checkOutcome();this.notify();return{ok:true,accepted:true,payment,roll,chance}}
  bypassAcceptance(taskId){const task=this.task(taskId);if(!task||task.status!=='awaiting_acceptance')return{ok:false};task.status='buried';this.quality=Math.max(0,this.quality-9);this.reputation=Math.max(0,this.reputation-3);advanceRoom(this.site,task.roomId);this.changedRooms.add(task.roomId);this.note(`${task.roomLabel}: работу зашили без приёмки. Срок выиграл, деньги спрятались вместе с актом.`,'danger');this.refreshTasks();this.checkOutcome();this.notify();return{ok:true,risk:'hidden_work',payment:0}}
  resolveEvent(choice='manage'){const event=this.pendingEvent;if(!event)return{ok:false};let success=true;if(choice==='pay'){const amount=Math.max(12,Math.abs(event.effect.budget||18));success=this.economy.cash>=amount;if(success){this.economy.cash-=amount;this.economy.spent+=amount;this.reputation=Math.min(100,this.reputation+1);this.note(`Проблему оплатили: −${amount} тыс. ₽. Она сразу стала техническим решением.`,'warning')}}else{const chance=.36+this.player.stats.competence/250+this.reputation/600;success=this.rng()<chance;if(success){this.xp+=8;this.quality=Math.min(100,this.quality+2);this.note('Проблему разобрали на месте. Все участники считают это своей заслугой.','good')}else{this.quality=Math.max(0,this.quality+(event.effect.quality||-3));this.reputation=Math.max(0,this.reputation-4);this.note('Решение породило уточняющий вопрос и два новых голосовых.','danger')}}this.pendingEvent=null;this.checkOutcome();this.notify();return{ok:true,success}}
  magicResolve(){if(this.day.elapsed<this.magicReadyAt)return{ok:false,reason:'cooldown',remaining:this.magicReadyAt-this.day.elapsed};this.magicReadyAt=this.day.elapsed+55;const roll=this.rng();if(this.pendingEvent&&roll<.4){this.pendingEvent=null;this.xp+=5;this.note('«Я в пути!» сработало: вопрос исчез из чата. Возможно, вместе с автором.','good');this.notify();return{ok:true,outcome:'solved'}}if(roll<.68){const task=[...this.tasks.values()].find(item=>item.status==='awaiting_acceptance');if(task){this.note('Кто-то поставил нужную подпись. Никто не признаётся.','good');return{ok:true,outcome:'accept',result:this.presentTask(task.id)}}}this.reputation=Math.max(0,this.reputation-5);this.nextEventAt=Math.min(this.nextEventAt,this.day.elapsed+5);this.note('«Порешать» открыло новый уровень проблемы, который раньше был заблокирован.','danger');this.notify();return{ok:true,outcome:'backfire'}}
  setPaused(value){this.day.paused=Boolean(value);this.notify()}
  finishDay(){this.day.finished=true;if(this.accepted>=4&&this.economy.cash>0){this.status='won';this.note('Смена закрыта: четыре фронта приняты, касса жива. Вы всё ещё генподрядчик.','good')}else{this.status='lost';this.note(`Смена закрыта: принято ${this.accepted}/4. Объект запомнил ваши решения.`,'danger')}this.notify()}
  checkOutcome(){if(this.reputation<=0||this.economy.cash<=0){this.status='lost';this.day.finished=true;this.note('Компания формально существует, но только в переписке.','danger')}else if(this.accepted>=4){this.status='won';this.day.finished=true;this.note('Полигон пройден: четыре работы приняты до конца смены.','good')}}
  snapshot(){return{version:this.version,seed:this.seed,day:{...this.day},economy:{...this.economy},quality:this.quality,reputation:this.reputation,xp:this.xp,accepted:this.accepted,status:this.status,site:this.site,tasks:[...this.tasks.values()],people:this.people,hazards:this.hazards,chat:this.chat,log:this.log}}
}
