export const marketEvents = [
  {
    id: "client-bankrupt",
    kicker: "Финансовая археология",
    title: "Заказчик разорился между авансом и обедом",
    text: "Банк уже забрал кофемашину, но финансовый директор просит закончить переговорную: вдруг кредиторы захотят красиво поговорить.",
    minHour: 18,
    weight: 5,
    options: [
      {
        id: "freeze-and-inventory",
        title: "Заморозить объект и описать всё",
        effect: "Команда уходит, материалы остаются под вашим контролем.",
        note: "Юристы называют это обеспечением сохранности, рабочие — длинным перекуром.",
        deltas: { budget: -35, quality: 0, trust: -4, time: 8 },
        scene: { actor: "client", actorCount: 1, hideSkill: "management", hideHours: 8, debris: 1 },
      },
      {
        id: "finish-for-creditors",
        title: "Достроить за свой счёт",
        effect: "Переговорная готова, а дебиторская задолженность получает дизайнерский свет.",
        note: "Портфолио растёт быстрее, чем вероятность оплаты.",
        deltas: { budget: -180, quality: 7, trust: 6, time: 12 },
        scene: { actor: "client", actorCount: 2, lightPower: 1.25 },
      },
    ],
  },
  {
    id: "client-vanished",
    kicker: "Режим тишины",
    title: "Заказчик пропал из всех мессенджеров",
    text: "Последнее сообщение — «делайте как договорились». Никто не помнит, как именно договорились, зато у каждого есть своя версия.",
    minHour: 12,
    weight: 6,
    options: [
      {
        id: "continue-by-brief",
        title: "Продолжать по утверждённому брифу",
        effect: "Работы идут, решения становятся уликами.",
        note: "Подписанный PDF внезапно признан самым взрослым человеком на объекте.",
        deltas: { budget: -55, quality: 4, trust: 2, time: 4 },
        scene: { actor: "architect", actorCount: 1, hideSkill: "management", hideHours: 5 },
      },
      {
        id: "stop-until-signal",
        title: "Остановиться до сигнала",
        effect: "Деньги целы, график приобретает философскую глубину.",
        note: "На стройке впервые слышно, как высыхает краска.",
        deltas: { budget: -10, quality: -2, trust: -3, time: 14 },
        scene: { hideSkill: "moving", hideHours: 10, debris: 2 },
      },
    ],
  },
  {
    id: "new-ceo-new-office",
    kicker: "Корпоративная тектоника",
    title: "У заказчика новый CEO и новое видение",
    text: "Вчера офис должен был быть демократичным. Сегодня CEO увидел дверь без таблички «CEO» и почувствовал угрозу культуре компании.",
    minHour: 28,
    weight: 5,
    options: [
      {
        id: "build-corner-office",
        title: "Вырезать кабинет у окна",
        effect: "Первое лицо довольно, опенспейс учится жить без дневного света.",
        note: "Плоская структура получила одну очень убедительную вершину.",
        deltas: { budget: -140, quality: -2, trust: 8, time: 16 },
        scene: { actor: "client", actorCount: 1, wallColor: "#24364b", lightPower: 0.82 },
      },
      {
        id: "defend-approved-concept",
        title: "Защитить утверждённую концепцию",
        effect: "Планировка сохраняется, отношения переходят в формат холодного остекления.",
        note: "Архитектор произносит слово «сценарий» двенадцать раз и выживает.",
        deltas: { budget: -20, quality: 6, trust: -7, time: 6 },
        scene: { actor: "architect", actorCount: 2, wallColor: "#d7d1c5" },
      },
    ],
  },
  {
    id: "budget-committee",
    kicker: "Коллективная ответственность",
    title: "Бюджетный комитет заметил бюджет",
    text: "Семь руководителей требуют сократить смету на двадцать процентов, не меняя площадь, качество, сроки и выражение лиц на рендерах.",
    minHour: 20,
    weight: 7,
    options: [
      {
        id: "value-engineering",
        title: "Провести честный value engineering",
        effect: "Дорогие решения заменены разумными, кроме кофейной зоны — там политика.",
        note: "Ведомость отделки худеет профессионально, без чудесных диет.",
        deltas: { budget: 95, quality: -5, trust: 5, time: 9 },
        scene: { actor: "architect", actorCount: 2, wallColor: "#c9c3b8" },
      },
      {
        id: "hide-costs-in-phases",
        title: "Разнести расходы по очередям",
        effect: "Текущий бюджет спасён, будущий бюджет ещё не знает, что он будущий.",
        note: "Excel показывает зелёный цвет и просит не задавать вопросов.",
        deltas: { budget: 135, quality: -8, trust: -5, time: 14 },
        scene: { hideSkill: "furniture", hideHours: 12, debris: 1 },
      },
    ],
  },
  {
    id: "landlord-base-build",
    kicker: "Граница ответственности",
    title: "Арендодатель вспомнил про base build",
    text: "Оказывается, вентиляция «была предусмотрена», но не воздухом, а пунктом в презентации отдела аренды.",
    minHour: 24,
    weight: 6,
    options: [
      {
        id: "negotiate-landlord-works",
        title: "Выбить работы из арендодателя",
        effect: "Инженеры арендодателя приходят, график делает шаг назад.",
        note: "Переговоры доказали: бесплатный воздух существует, но поставляется позже.",
        deltas: { budget: 120, quality: 3, trust: 3, time: 18 },
        scene: { actor: "inspector", actorCount: 2, hideSkill: "electric", hideHours: 7 },
      },
      {
        id: "fix-base-build-yourself",
        title: "Исправить своими силами",
        effect: "Система работает, собственник здания благодарит вас отсутствием компенсации.",
        note: "Чужой актив стал лучше за ваши деньги — классика гостеприимства.",
        deltas: { budget: -210, quality: 8, trust: 5, time: 10 },
        scene: { actor: "delivery", actorCount: 1, lightPower: 1.15, debris: 2 },
      },
    ],
  },
  {
    id: "designer-signature-color",
    kicker: "Авторский надзор",
    title: "Дизайнер нашёл фирменный бежевый",
    text: "Новый оттенок отличается от старого только уверенностью автора и сроком поставки из Италии.",
    minHour: 15,
    weight: 7,
    options: [
      {
        id: "approve-special-beige",
        title: "Заказать правильный оттенок",
        effect: "Стены обретают нюанс, календарь — дополнительную неделю.",
        note: "При искусственном свете разницу видит только дизайнер, но очень громко.",
        deltas: { budget: -85, quality: 7, trust: 4, time: 20 },
        scene: { actor: "architect", actorCount: 1, hideSkill: "paint", hideHours: 8, wallColor: "#cfc3ae" },
      },
      {
        id: "mix-local-equivalent",
        title: "Заколеровать местный аналог",
        effect: "Цвет почти тот, зато он существует сегодня.",
        note: "Образец подписан «временный постоянный» и спрятан от автора.",
        deltas: { budget: -20, quality: -3, trust: -2, time: 3 },
        scene: { wallColor: "#d2c5b0", debris: 1 },
      },
    ],
  },
  {
    id: "fire-code-corridor",
    kicker: "Нормативный поворот",
    title: "Пожарный инспектор измерил коридор",
    text: "Коридор на рендере широкий, в реальности узкий, а в протоколе — особенно узкий.",
    minHour: 22,
    weight: 6,
    options: [
      {
        id: "rebuild-egress-route",
        title: "Переделать путь эвакуации",
        effect: "Люди смогут выйти, бюджет уже вышел.",
        note: "Красивый пуф первым пожертвовал собой ради пожарной безопасности.",
        deltas: { budget: -160, quality: 5, trust: 7, time: 15 },
        scene: { actor: "inspector", actorCount: 2, hideSkill: "moving", hideHours: 6, debris: 3 },
      },
      {
        id: "request-compensating-measures",
        title: "Согласовать компенсирующие меры",
        effect: "Добавлены датчики, знаки и папка, способная остановить огонь массой.",
        note: "Безопасность улучшилась, главным образом документально.",
        deltas: { budget: -75, quality: 1, trust: -3, time: 11 },
        scene: { actor: "inspector", actorCount: 1, lightPower: 1.3 },
      },
    ],
  },
  {
    id: "import-customs-delay",
    kicker: "Глобальная логистика",
    title: "Импортный свет застрял на таможне",
    text: "Контейнер физически рядом, юридически далеко и эмоционально уже не ваш.",
    minHour: 30,
    weight: 6,
    options: [
      {
        id: "wait-for-original-lights",
        title: "Ждать оригинальные светильники",
        effect: "Проект сохраняет концепцию и теряет несколько рассветов.",
        note: "Трек-номер стал самым популярным дашбордом проекта.",
        deltas: { budget: -30, quality: 8, trust: -2, time: 24 },
        scene: { hideSkill: "electric", hideHours: 14, lightPower: 0.55 },
      },
      {
        id: "buy-local-lights",
        title: "Взять местный свет",
        effect: "В офисе светло, в мудборде — траур.",
        note: "Температура света называется «примерно деловая».",
        deltas: { budget: -70, quality: -4, trust: 3, time: 4 },
        scene: { actor: "delivery", actorCount: 2, lightPower: 1.1 },
      },
    ],
  },
  {
    id: "chair-sample-revolt",
    kicker: "Эргономическая демократия",
    title: "Сотрудники проголосовали против кресел",
    text: "Пилотный образец признан неудобным после того, как на нём пять минут посидел директор по счастью.",
    minHour: 26,
    weight: 5,
    options: [
      {
        id: "run-chair-pilot",
        title: "Провести нормальный пилот",
        effect: "Выбор займёт время, зато спины перестанут участвовать в конфликте.",
        note: "Сотрудники тестируют двенадцать кресел и внезапно любят совещания.",
        deltas: { budget: -45, quality: 7, trust: 6, time: 12 },
        scene: { actor: "delivery", actorCount: 2, hideSkill: "furniture", hideHours: 5 },
      },
      {
        id: "keep-approved-chairs",
        title: "Оставить утверждённую модель",
        effect: "Поставка идёт по плану, корпоративная йога получает новых клиентов.",
        note: "В договоре не было пункта о счастье поясницы.",
        deltas: { budget: 20, quality: -7, trust: -6, time: 2 },
        scene: { actor: "delivery", actorCount: 3, debris: 1 },
      },
    ],
  },
  {
    id: "vacancy-market-shift",
    kicker: "Рынок передумал",
    title: "В соседнем здании подешевела аренда",
    text: "Заказчик увидел свободный этаж с готовой отделкой и теперь сравнивает вашу стройку с чужой фотографией без дефектов крупным планом.",
    minHour: 32,
    weight: 4,
    options: [
      {
        id: "prove-total-cost",
        title: "Посчитать полную стоимость переезда",
        effect: "Проект остаётся, доверие возвращается через таблицу.",
        note: "Самым убедительным элементом дизайна оказался штраф за расторжение аренды.",
        deltas: { budget: -25, quality: 1, trust: 8, time: 7 },
        scene: { actor: "client", actorCount: 2 },
      },
      {
        id: "offer-scope-cut",
        title: "Предложить срочное удешевление",
        effect: "Заказчик остаётся, интерьер становится свидетелем компромисса.",
        note: "Терраццо переводится в категорию «идея для второй очереди».",
        deltas: { budget: 110, quality: -9, trust: 2, time: 5 },
        scene: { wallColor: "#b8b8b2", lightPower: 0.9 },
      },
    ],
  },
  {
    id: "coworking-comparison",
    kicker: "Гибкий конкурент",
    title: "Финдиректор открыл калькулятор коворкинга",
    text: "Он умножил красивую месячную ставку на число сотрудников и не стал читать строку мелким шрифтом. Проект объявлен подозрительно капитальным.",
    minHour: 35,
    weight: 5,
    options: [
      {
        id: "model-five-years",
        title: "Сравнить пять лет владения",
        effect: "Fit-out снова выглядит разумно, особенно на четвёртом листе модели.",
        note: "Будущее компании впервые официально продлено до пяти лет.",
        deltas: { budget: -18, quality: 2, trust: 7, time: 6 },
        scene: { actor: "client", actorCount: 1, hideSkill: "management", hideHours: 3 },
      },
      {
        id: "copy-coworking-style",
        title: "Добавить неон и пуфы",
        effect: "Офис выглядит гибким, хотя стены всё ещё капитальные.",
        note: "Слово COMMUNITY нанесено на стену, сообщество ожидается позже.",
        deltas: { budget: -90, quality: -2, trust: 5, time: 9 },
        scene: { wallColor: "#4c315f", lightPower: 1.35, debris: 1 },
      },
    ],
  },
  {
    id: "smoking-room-rnd",
    kicker: "Организационная инновация",
    title: "Курилку признали настоящим R&D",
    text: "Там приняли три ключевых решения, пока официальные переговорные бронировали для обсуждения правил бронирования.",
    minHour: 16,
    weight: 5,
    options: [
      {
        id: "build-outdoor-lab",
        title: "Сделать уличную лабораторию",
        effect: "Неформальные идеи получают навес, свет и неожиданно строгую смету.",
        note: "Инновации теперь проходят по ведомости как малая архитектурная форма.",
        deltas: { budget: -75, quality: 5, trust: 6, time: 10 },
        scene: { actor: "architect", actorCount: 1, lightPower: 1.15 },
      },
      {
        id: "ban-and-add-whiteboard",
        title: "Запретить и поставить доску",
        effect: "Воздух чище, идеи уходят на лестницу без маркеров.",
        note: "R&D закрыт за нарушение брендбука и режима проветривания.",
        deltas: { budget: -12, quality: 1, trust: -5, time: 2 },
        scene: { hideSkill: "management", hideHours: 5, debris: 0 },
      },
    ],
  },
  {
    id: "imposed-contractor",
    kicker: "Проверенный человек",
    title: "Заказчик навязал своего подрядчика",
    text: "Подрядчик проверенный: дважды не уложился в срок и каждый раз был проверен лично.",
    minHour: 14,
    weight: 7,
    options: [
      {
        id: "accept-with-quality-gates",
        title: "Принять с жёсткими контрольными точками",
        effect: "Подрядчик работает медленнее, зато дефекты появляются при свидетелях.",
        note: "Фотофиксация превращает «так и было» в короткий жанр.",
        deltas: { budget: -40, quality: 4, trust: 5, time: 9 },
        scene: { actor: "inspector", actorCount: 1, hideSkill: "management", hideHours: 4, debris: 2 },
      },
      {
        id: "refuse-favorite-contractor",
        title: "Отказать и провести тендер",
        effect: "Цена прозрачнее, атмосфера заметно плотнее.",
        note: "Тендер выигрывает компетенция и проигрывает семейный чат.",
        deltas: { budget: 65, quality: 7, trust: -8, time: 13 },
        scene: { actor: "client", actorCount: 2, hideSkill: "moving", hideHours: 6 },
      },
    ],
  },
  {
    id: "access-hours-cut",
    kicker: "Режим здания",
    title: "Арендодатель запретил шуметь днём",
    text: "Сверлить можно с 23:00 до 06:00, но лифт для материалов отдыхает с 22:30 до 06:30.",
    minHour: 19,
    weight: 6,
    options: [
      {
        id: "buy-night-window",
        title: "Оплатить ночной доступ",
        effect: "Лифт бодрствует, смета теряет сон.",
        note: "Кнопка грузового лифта официально стала премиальной услугой.",
        deltas: { budget: -95, quality: 2, trust: 4, time: 6 },
        scene: { actor: "delivery", actorCount: 2, lightPower: 0.72 },
      },
      {
        id: "switch-to-quiet-works",
        title: "Переставить тихие работы вперёд",
        effect: "График усложняется, объект временно превращается в выставку нераспакованной мебели.",
        note: "План производства работ теперь похож на расписание аэропорта.",
        deltas: { budget: -25, quality: 0, trust: -1, time: 12 },
        scene: { hideSkill: "electric", hideHours: 8, actor: "delivery", actorCount: 1, debris: 2 },
      },
    ],
  },
  {
    id: "furniture-factory-rescheduled",
    kicker: "Серийная уникальность",
    title: "Фабрика перенесла вашу мебель в следующий квартал",
    text: "Производство загружено заказом на точно такие же столы для клиента, который внёс предоплату чуть более убедительно.",
    minHour: 38,
    weight: 5,
    options: [
      {
        id: "rent-temporary-furniture",
        title: "Арендовать временную мебель",
        effect: "Офис открывается вовремя и выглядит как коворкинг после переезда.",
        note: "Разные стулья объявлены кураторской коллекцией.",
        deltas: { budget: -115, quality: -3, trust: 7, time: 3 },
        scene: { actor: "delivery", actorCount: 3, wallColor: "#d9d4ca", debris: 2 },
      },
      {
        id: "wait-for-custom-furniture",
        title: "Ждать заказную мебель",
        effect: "Интерьер будет цельным, запуск — историческим.",
        note: "Столы ещё не существуют, но уже соответствуют дизайн-коду.",
        deltas: { budget: -20, quality: 8, trust: -6, time: 22 },
        scene: { hideSkill: "furniture", hideHours: 16 },
      },
    ],
  },
  {
    id: "launch-date-moved",
    kicker: "Праздничный менеджмент",
    title: "Открытие перенесли на вчера",
    text: "Маркетинг уже пригласил прессу, CEO купил ножницы, а потолок пока выражает конструктивную честность.",
    minHour: 34,
    weight: 7,
    options: [
      {
        id: "stage-safe-opening",
        title: "Открыть только готовую зону",
        effect: "Гости видят красивую часть и очень убедительную временную стену.",
        note: "Маршрут экскурсии спроектирован с точностью побега из лабиринта.",
        deltas: { budget: -80, quality: 1, trust: 6, time: 5 },
        scene: { actor: "client", actorCount: 3, wallColor: "#f0eadf", debris: 0 },
      },
      {
        id: "rush-everything",
        title: "Ускорить всё сразу",
        effect: "Офис открывается целиком, список недоделок тоже.",
        note: "Малярный скотч входит в новую айдентику пространства.",
        deltas: { budget: -170, quality: -9, trust: 3, time: -8 },
        scene: { actor: "delivery", actorCount: 4, hideSkill: "cleaning", hideHours: 4, debris: 4 },
      },
    ],
  },
  {
    id: "sublease-downsize",
    kicker: "Оптимизация площади",
    title: "Заказчик решил сдать половину офиса",
    text: "Гибридная работа победила ровно после подписания договора на десять лет. Теперь нужен отдельный вход там, где стоит кухня.",
    minHour: 42,
    weight: 4,
    options: [
      {
        id: "split-floor-properly",
        title: "Спроектировать честное деление",
        effect: "Появляются две автономные части и один общий спор о ресепшене.",
        note: "Инженерные системы знакомятся с понятием имущественных границ.",
        deltas: { budget: -220, quality: 6, trust: 7, time: 20 },
        scene: { actor: "architect", actorCount: 2, wallColor: "#7f8b8c", debris: 3 },
      },
      {
        id: "install-quick-divider",
        title: "Поставить быструю перегородку",
        effect: "Площади разделены визуально, разговоры — нет.",
        note: "Акустическая приватность перенесена в следующий договор аренды.",
        deltas: { budget: -65, quality: -7, trust: 1, time: 6 },
        scene: { wallColor: "#a7afb3", hideSkill: "moving", hideHours: 4, debris: 2 },
      },
    ],
  },
  {
    id: "broker-market-tour",
    kicker: "Экспертная экскурсия",
    title: "Брокер привёл заказчика смотреть чужие офисы",
    text: "После трёх лобби и одного бесплатного капучино заказчик требует больше мрамора, меньше бюджета и вид как на рендерах конкурентов.",
    minHour: 25,
    weight: 5,
    options: [
      {
        id: "refresh-benchmark",
        title: "Обновить рыночный benchmark",
        effect: "Часть решений усиливается, декоративный шум остаётся в чужом лобби.",
        note: "Мрамор проиграл переговорной с хорошей акустикой со счётом 0:1.",
        deltas: { budget: -40, quality: 6, trust: 5, time: 8 },
        scene: { actor: "architect", actorCount: 2, lightPower: 1.08 },
      },
      {
        id: "imitate-premium-lobby",
        title: "Скопировать премиальное лобби",
        effect: "Вход становится дороже, рабочие места — ближе друг к другу.",
        note: "Первое впечатление занимает последние свободные метры.",
        deltas: { budget: -130, quality: -1, trust: 6, time: 13 },
        scene: { actor: "delivery", actorCount: 2, wallColor: "#35383b", lightPower: 1.22 },
      },
    ],
  },
];
