export const metaEvents = [
  {
    id: "boss-borrows-brigade",
    kicker: "Ресурсная синергия",
    title: "Начальство временно отбирает людей",
    text: "Директору срочно понадобилась ваша бригада на другом объекте. Слово «временно» произнесено с той же уверенностью, что и «бюджет согласован».",
    minHour: 6,
    weight: 7,
    options: [
      {
        id: "release-brigade",
        title: "Отдать бригаду",
        effect: "Рабочие исчезают со стройки, зато начальство запоминает вашу управляемость.",
        note: "Две смены без основной бригады.",
        deltas: { budget: 0, quality: -3, trust: 5, time: 8 },
        scene: { actor: "boss", actorCount: 1, hideSkill: "moving", hideHours: 8 },
      },
      {
        id: "defend-brigade",
        title: "Закрыть дверь прорабской",
        effect: "Люди остаются, отношения с вертикалью становятся горизонтальными.",
        note: "Объект не встает, но разговор на годовой оценке уже написан.",
        deltas: { budget: -20, quality: 2, trust: -6, time: -2 },
        scene: { actor: "boss", actorCount: 2 },
      },
    ],
  },
  {
    id: "foreman-disappears",
    kicker: "Кадровый риск",
    title: "Прораб ушел в запой",
    text: "Прораб не вышел на связь. Это не колорит профессии, а опасная зависимость: объект теряет управление, человеку нужна помощь.",
    minHour: 10,
    weight: 5,
    options: [
      {
        id: "arrange-help",
        title: "Организовать помощь и замену",
        effect: "Компания оплачивает специалиста и выводит трезвого сменного прораба.",
        note: "Дороже сегодня, безопаснее для человека и стройки завтра.",
        deltas: { budget: -90, quality: 3, trust: 6, time: 4 },
        scene: { hideSkill: "management", hideHours: 4, debris: 1 },
      },
      {
        id: "pretend-normal",
        title: "Назвать это удаленкой",
        effect: "Отчетность спасена на один день, управление — нет.",
        note: "Бригада работает по воспоминаниям о последней планерке.",
        deltas: { budget: -15, quality: -10, trust: -8, time: 10 },
        scene: { hideSkill: "management", hideHours: 10, debris: 4 },
      },
    ],
  },
  {
    id: "foreman-returns-philosopher",
    kicker: "Возвращение сотрудника",
    title: "Прораб вернулся философом",
    text: "После лечения прораб вернулся трезвым, серьезным и спрашивает, существует ли дедлайн вне нашего восприятия. Романтики нет — нужен аккуратный возврат к работе.",
    minHour: 24,
    weight: 3,
    options: [
      {
        id: "staged-return",
        title: "Вернуть поэтапно",
        effect: "Прораб начинает с коротких смен и чек-листов, философия не мешает охране труда.",
        note: "Качество растет, график получает небольшую паузу.",
        deltas: { budget: -35, quality: 6, trust: 7, time: 3 },
        scene: { actor: "architect", actorCount: 1, hideSkill: "management", hideHours: 3 },
      },
      {
        id: "instant-full-shift",
        title: "Сразу дать две смены",
        effect: "Экзистенциальный надзор начинается немедленно и быстро перегружает человека.",
        note: "Плохая кадровая практика маскируется словом «доверие».",
        deltas: { budget: 10, quality: -5, trust: -7, time: -1 },
        scene: { hideSkill: "management", hideHours: 6, debris: 2 },
      },
    ],
  },
  {
    id: "corporate-reorganization",
    kicker: "Новая оргструктура",
    title: "Ваш департамент снова реорганизовали",
    text: "Теперь вы подчиняетесь Дирекции пространственных трансформаций. Ее руководитель пока не назначен, но его подпись уже обязательна.",
    minHour: 14,
    weight: 6,
    options: [
      {
        id: "follow-new-chain",
        title: "Пройти все согласования",
        effect: "Документы идеальны, стройка несколько часов любуется документами.",
        note: "Доверие начальства куплено временем проекта.",
        deltas: { budget: -10, quality: 1, trust: 5, time: 7 },
        scene: { actor: "boss", actorCount: 2, hideSkill: "management", hideHours: 7 },
      },
      {
        id: "keep-building",
        title: "Продолжить по старой схеме",
        effect: "Стены строятся быстрее оргструктуры.",
        note: "Результат виден, субординация тоже заметила.",
        deltas: { budget: 0, quality: 2, trust: -5, time: -2 },
        scene: { wallColor: "#d7ddd2" },
      },
    ],
  },
  {
    id: "tender-three-quotes",
    kicker: "Закупочная магия",
    title: "Тендерный отдел требует третье КП",
    text: "Два предложения уже есть. Третье должно быть дешевле победителя, дороже рынка и от компании, которая не должна победить.",
    minHour: 18,
    weight: 7,
    options: [
      {
        id: "run-honest-mini-tender",
        title: "Провести честный мини-тендер",
        effect: "Появляется нормальный подрядчик и ненормальное количество таблиц.",
        note: "Экономия приходит позже, чем хотелось, но без фокусов.",
        deltas: { budget: 45, quality: 4, trust: 4, time: 6 },
        scene: { actor: "client", actorCount: 2, hideSkill: "management", hideHours: 6 },
      },
      {
        id: "buy-before-approval",
        title: "Купить до протокола",
        effect: "Материалы уже на объекте, а тендерный комитет еще выбирает шрифт протокола.",
        note: "Срок спасен ценой процедурного инфаркта.",
        deltas: { budget: -30, quality: 1, trust: -7, time: -4 },
        scene: { debris: 3 },
      },
    ],
  },
  {
    id: "own-office-never-finished",
    kicker: "Дом сапожника",
    title: "Собственный офис снова не достроен",
    text: "Вы успешно сдаете чужие офисы. В вашем офисе переговорная второй год обозначена малярной лентой, потому что клиенты всегда важнее.",
    minHour: 20,
    weight: 6,
    options: [
      {
        id: "weekend-renovation",
        title: "Устроить субботник",
        effect: "Сотрудники красят одну стену и начинают искать вакансии с готовыми стенами.",
        note: "Офис чуть лучше, мораль чуть сложнее.",
        deltas: { budget: -25, quality: 2, trust: -3, time: 3 },
        scene: { actorCount: 3, hideSkill: "paint", hideHours: 3, wallColor: "#b7c7b0" },
      },
      {
        id: "postpone-own-office",
        title: "Снова отложить",
        effect: "Малярная лента получает статус постоянной перегородки.",
        note: "Клиентский объект не страдает. Ваш офис продолжает развиваться безуспешно.",
        deltas: { budget: 20, quality: -2, trust: 1, time: -1 },
        scene: { wallColor: "#9aa0a3", debris: 2 },
      },
    ],
  },
  {
    id: "accounting-freezes-payment",
    kicker: "Финансовый контроль",
    title: "Бухгалтерия заморозила оплату",
    text: "В акте написано «краска белая», а в счете — «белая матовая». Для бухгалтерии это две разные вселенные и ни одной проводки.",
    minHour: 16,
    weight: 7,
    options: [
      {
        id: "redo-documents",
        title: "Переделать пакет",
        effect: "Оплата пройдет после ритуала из подписей, печатей и тихого вздоха.",
        note: "Подрядчик ждет, документы хорошеют.",
        deltas: { budget: -8, quality: 0, trust: 3, time: 5 },
        scene: { hideSkill: "paint", hideHours: 5 },
      },
      {
        id: "advance-own-money",
        title: "Закрыть из резерва",
        effect: "Работы продолжаются, резерв превращается в воспоминание.",
        note: "Бригада довольна, финансовый директор готовит вопросы.",
        deltas: { budget: -75, quality: 2, trust: -2, time: -3 },
        scene: { actor: "boss", actorCount: 1 },
      },
    ],
  },
  {
    id: "pr-showcase-visit",
    kicker: "Позитивная повестка",
    title: "PR назначил съемку готового офиса",
    text: "Съемка через четыре часа. Офис готов на шестьдесят процентов, что в презентации уже округлено до ста десяти.",
    minHour: 22,
    weight: 5,
    options: [
      {
        id: "stage-one-zone",
        title: "Собрать один идеальный ракурс",
        effect: "Одна зона сияет, за камерой тихо существует реальность.",
        note: "PR получает кадр, уборщики — ускоренный курс телепортации мусора.",
        deltas: { budget: -30, quality: 1, trust: 4, time: 3 },
        scene: { actor: "client", actorCount: 2, hideSkill: "cleaning", hideHours: 3, lightPower: 1.5, debris: -3 },
      },
      {
        id: "show-real-site",
        title: "Показать стройку честно",
        effect: "В ролик попадают кабели, каски и редкий корпоративный реализм.",
        note: "PR недоволен, профессионалы внезапно доверяют больше.",
        deltas: { budget: 0, quality: 2, trust: 6, time: 0 },
        scene: { actor: "architect", actorCount: 2, debris: 4, lightPower: 0.8 },
      },
    ],
  },
  {
    id: "kpi-moves-target",
    kicker: "Управление эффективностью",
    title: "KPI обновились задним числом",
    text: "Раньше главным был срок. Теперь главное — экономия, качество, счастье заказчика и отсутствие компромиссов. Вес каждого показателя засекречен.",
    minHour: 28,
    weight: 6,
    options: [
      {
        id: "optimize-visible-metric",
        title: "Оптимизировать красивую цифру",
        effect: "Дашборд зеленеет быстрее свежей краски.",
        note: "Премия ближе, реальный объект слегка дальше.",
        deltas: { budget: 35, quality: -5, trust: -3, time: 2 },
        scene: { actor: "boss", actorCount: 1, wallColor: "#d9efc2" },
      },
      {
        id: "protect-project-balance",
        title: "Держать баланс проекта",
        effect: "Цифры спорные, офис получается пригодным для людей.",
        note: "Не лучший слайд, зато хороший объект.",
        deltas: { budget: -15, quality: 6, trust: 5, time: 2 },
        scene: { actor: "client", actorCount: 1, lightPower: 1.15 },
      },
    ],
  },
  {
    id: "surprise-compliance-audit",
    kicker: "Контроль контроля",
    title: "На объект пришел внезапный аудит",
    text: "Инспектор улыбается так, будто уже нашел нарушение, но хочет дать вам шанс найти его первым.",
    minHour: 30,
    weight: 6,
    options: [
      {
        id: "open-all-records",
        title: "Открыть журналы и объект",
        effect: "Аудит находит мелочи и видит, что вы не прячете крупное.",
        note: "Исправления стоят денег, доверие — тоже актив.",
        deltas: { budget: -55, quality: 5, trust: 7, time: 4 },
        scene: { actor: "inspector", actorCount: 2, hideSkill: "electric", hideHours: 4, lightPower: 0.9 },
      },
      {
        id: "escort-to-perfect-zone",
        title: "Водить по идеальному маршруту",
        effect: "Маршрут заканчивается там, где инспектор решает открыть не ту дверь.",
        note: "Краткая экономия превращается в длинный акт.",
        deltas: { budget: -90, quality: -7, trust: -10, time: 8 },
        scene: { actor: "inspector", actorCount: 3, debris: 5, lightPower: 1.4 },
      },
    ],
  },
  {
    id: "career-promotion-dilemma",
    kicker: "Карьерное окно",
    title: "Вам предлагают повышение посреди сдачи",
    text: "Новая должность называется «руководитель направления». Направление пока одно: подальше от ответственности за этот объект.",
    minHour: 34,
    weight: 4,
    options: [
      {
        id: "accept-promotion",
        title: "Принять и передать объект",
        effect: "Визитка становится солиднее, стройка на время теряет память.",
        note: "Карьерный шаг вперед, проектный шаг в сторону.",
        deltas: { budget: 40, quality: -6, trust: -8, time: 7 },
        scene: { actor: "boss", actorCount: 2, hideSkill: "management", hideHours: 7 },
      },
      {
        id: "finish-before-moving",
        title: "Сначала сдать объект",
        effect: "Повышение может уйти, зато команда видит руководителя на площадке.",
        note: "Карьера задерживается на один качественный офис.",
        deltas: { budget: -10, quality: 5, trust: 8, time: 1 },
        scene: { actor: "architect", actorCount: 2 },
      },
    ],
  },
  {
    id: "quarter-end-budget",
    kicker: "Конец квартала",
    title: "Нужно срочно освоить бюджет",
    text: "Начальство обнаружило деньги, которые исчезнут в полночь. Предлагается купить что-нибудь стратегическое, желательно до обеда.",
    minHour: 26,
    weight: 5,
    options: [
      {
        id: "buy-useful-stock",
        title: "Закупить типовые материалы",
        effect: "Склад получает запас, проект — шанс не ждать следующую поставку.",
        note: "Полезно, хотя слово «освоить» все равно звучит подозрительно.",
        deltas: { budget: -110, quality: 3, trust: 3, time: -3 },
        scene: { actor: "boss", actorCount: 1, debris: 3 },
      },
      {
        id: "return-unused-budget",
        title: "Вернуть остаток",
        effect: "Компания экономит деньги и навсегда уменьшает ваш следующий лимит.",
        note: "Финансово разумно, организационно наказуемо.",
        deltas: { budget: 80, quality: 0, trust: -4, time: 0 },
        scene: { actor: "boss", actorCount: 2 },
      },
    ],
  },
  {
    id: "executive-furniture-pivot",
    kicker: "Высочайший дизайн",
    title: "Директор лично переставил кресло на плане",
    text: "Одно кресло сдвинуто на метр. За ним переезжают розетки, светильники, перегородка и ваше внутреннее спокойствие.",
    minHour: 32,
    weight: 6,
    options: [
      {
        id: "rebuild-for-chair",
        title: "Перестроить вокруг кресла",
        effect: "Кресло достигает идеальной позиции, инженерные сети — нового жизненного этапа.",
        note: "Дорого, долго, зато директор садится без вопросов.",
        deltas: { budget: -130, quality: 1, trust: 7, time: 9 },
        scene: { actor: "boss", actorCount: 1, hideSkill: "electric", hideHours: 5, lightPower: 1.25, debris: 4 },
      },
      {
        id: "mockup-and-negotiate",
        title: "Показать макет и последствия",
        effect: "Директор видит стоимость метра перемещения и внезапно любит прежний вариант.",
        note: "Час на макет экономит смену переделок.",
        deltas: { budget: -12, quality: 3, trust: 2, time: 1 },
        scene: { actor: "architect", actorCount: 2, hideSkill: "furniture", hideHours: 1 },
      },
    ],
  },
  {
    id: "strategy-workshop-in-site",
    kicker: "Стратегическая сессия",
    title: "Начальство проводит воркшоп прямо на объекте",
    text: "Двадцать руководителей хотят обсуждать офис будущего внутри офиса, где пока нет света, стульев и настоящего.",
    minHour: 38,
    weight: 4,
    options: [
      {
        id: "pause-and-host",
        title: "Остановить работы и принять гостей",
        effect: "Стройка замирает, зато флипчарт производит семь новых приоритетов.",
        note: "Срок страдает ради коллективного ощущения движения.",
        deltas: { budget: -45, quality: -1, trust: 6, time: 6 },
        scene: { actor: "boss", actorCount: 4, hideSkill: "moving", hideHours: 6, lightPower: 1.5, debris: -2 },
      },
      {
        id: "issue-hard-hats",
        title: "Выдать каски и не останавливаться",
        effect: "Стратегия становится громче перфоратора, но не убедительнее.",
        note: "Работы идут, руководители впервые видят, что такое работы.",
        deltas: { budget: -18, quality: 2, trust: -2, time: -1 },
        scene: { actor: "boss", actorCount: 4, debris: 3, lightPower: 0.85 },
      },
    ],
  },
];
