export const workforceEvents = [
  {
    id: 'migracionnaya-proverka',
    kicker: 'Документы любят порядок',
    title: 'Миграционная служба пришла раньше кофе',
    text: 'Проверяющие вежливо просят документы у бригады. Бригада столь же вежливо перестаёт существовать в этой комнате.',
    minHour: 6,
    weight: 8,
    options: [
      {
        id: 'legalnaya-pauza',
        title: 'Остановить работы и всё сверить',
        effect: 'Юрист собирает папку, а рабочие ждут окончания бумажного спектакля.',
        note: 'Дороже и медленнее, зато заказчик видит управляемый процесс.',
        deltas: { budget: -90, quality: 1, trust: 5, time: 5 },
        scene: { actor: 'inspector', actorCount: 2, hideSkill: 'moving', hideHours: 5 },
      },
      {
        id: 'perebrosit-brigadu',
        title: 'Срочно заменить бригаду',
        effect: 'На площадку приезжают новые люди и сначала ищут, где здесь вообще стены.',
        note: 'Темп почти сохранён, но качество знакомства с проектом вызывает вопросы.',
        deltas: { budget: -160, quality: -4, trust: -2, time: 2 },
        scene: { actor: 'worker', actorCount: 3, hideSkill: 'moving', hideHours: 2, debris: 1 },
      },
    ],
  },
  {
    id: 'siloviki-na-obekte',
    kicker: 'Час формы',
    title: 'Силовики перепутали этаж, но уже вошли',
    text: 'Люди в форме ищут соседнюю компанию. Ваш прораб почему-то внезапно вспоминает, что у него обед.',
    minHour: 10,
    weight: 5,
    options: [
      {
        id: 'pokazat-dokumenty',
        title: 'Показать журнал допуска',
        effect: 'Проверка быстро убеждается, что ваш главный секрет — сорванный график.',
        note: 'Короткая остановка укрепляет доверие к прозрачности площадки.',
        deltas: { budget: -25, quality: 0, trust: 4, time: 2 },
        scene: { actor: 'police', actorCount: 3, hideSkill: 'management', hideHours: 2 },
      },
      {
        id: 'zakryt-etazh',
        title: 'Закрыть этаж до выяснения',
        effect: 'Все дисциплинированно уходят, включая тех, кого никто не просил.',
        note: 'Безопасно, официально и совершенно несовместимо со сроками.',
        deltas: { budget: -40, quality: 1, trust: 1, time: 6 },
        scene: { actor: 'police', actorCount: 4, hideSkill: 'management', hideHours: 6 },
      },
    ],
  },
  {
    id: 'inspektor-bez-preduprezhdeniya',
    kicker: 'Плановая внезапность',
    title: 'Инспектор обнаружил площадку',
    text: 'Инспектор фотографирует удлинитель так, будто это редкий хищник. Электрик начинает говорить исключительно нормативами.',
    minHour: 8,
    weight: 7,
    options: [
      {
        id: 'ustranit-na-meste',
        title: 'Исправить замечания при нём',
        effect: 'Бригада устраивает показательное наведение порядка с выражением глубокой осознанности.',
        note: 'Тратим деньги, но получаем качество и спокойный акт.',
        deltas: { budget: -70, quality: 5, trust: 3, time: 3 },
        scene: { actor: 'inspector', actorCount: 1, hideSkill: 'electric', hideHours: 3, lightPower: 0.75, debris: -2 },
      },
      {
        id: 'sporit-po-procedure',
        title: 'Оспорить процедуру',
        effect: 'Прораб открывает папку «Переписка» и превращает стройку в юридический сериал.',
        note: 'Экономим сейчас, но заказчик слышит каждую серию.',
        deltas: { budget: -15, quality: -2, trust: -5, time: 5 },
        scene: { actor: 'inspector', actorCount: 2, hideSkill: 'management', hideHours: 5 },
      },
    ],
  },
  {
    id: 'rabochih-peremanili',
    kicker: 'Рынок труда работает',
    title: 'Соседний этаж предложил обед получше',
    text: 'Двое отделочников ушли к конкурентам после фразы «у нас чай не в пакетиках». Капитализм снова победил календарный план.',
    minHour: 12,
    weight: 8,
    options: [
      {
        id: 'kontrpredlozhenie',
        title: 'Сделать контрпредложение',
        effect: 'Рабочие возвращаются с новой ставкой и заметно улучшенной осанкой.',
        note: 'Дорого, зато навык и темп остаются на площадке.',
        deltas: { budget: -130, quality: 2, trust: 1, time: 1 },
        scene: { actor: 'worker', actorCount: 2 },
      },
      {
        id: 'iskat-novyh',
        title: 'Искать новых людей',
        effect: 'К вечеру приходит бригада, уверенная, что зелёный и бирюзовый — один технический цвет.',
        note: 'Дешевле удержания, но знакомство с палитрой займёт время.',
        deltas: { budget: -55, quality: -4, trust: -2, time: 5 },
        scene: { actor: 'worker', actorCount: 3, hideSkill: 'paint', hideHours: 5, wallColor: '#66a89c' },
      },
    ],
  },
  {
    id: 'nochnaya-smena-ischezla',
    kicker: 'Тихая смена',
    title: 'Ночная бригада растворилась к рассвету',
    text: 'На площадке остались три стаканчика, один шуруповёрт и философский вопрос: была ли бригада вообще.',
    minHour: 18,
    weight: 6,
    options: [
      {
        id: 'podnyat-rezerv',
        title: 'Поднять резервную бригаду',
        effect: 'Резерв приезжает сонный, дорогой и очень удивлённый слову «резерв».',
        note: 'Сроки почти спасены ценой ночного тарифа.',
        deltas: { budget: -180, quality: -1, trust: 2, time: 2 },
        scene: { actor: 'worker', actorCount: 4, hideSkill: 'furniture', hideHours: 2 },
      },
      {
        id: 'zhdat-vozvrashcheniya',
        title: 'Ждать объяснений',
        effect: 'К обеду приходит голосовое сообщение длиной в одиннадцать минут и без глаголов.',
        note: 'Бюджет цел, график — уже нет.',
        deltas: { budget: -20, quality: 0, trust: -4, time: 8 },
        scene: { hideSkill: 'furniture', hideHours: 8, debris: 2 },
      },
    ],
  },
  {
    id: 'konflikt-dvuh-brigad',
    kicker: 'Смежники встретились',
    title: 'Маляры и электрики делят одну стену',
    text: 'Каждая бригада считает стену своей, а отверстия другой стороны — личным оскорблением проектной документации.',
    minHour: 9,
    weight: 9,
    options: [
      {
        id: 'razvesti-po-smenam',
        title: 'Развести по сменам',
        effect: 'Стена получает расписание плотнее, чем переговорная заказчика.',
        note: 'Конфликт снят, но последовательность работ растягивается.',
        deltas: { budget: -35, quality: 3, trust: 2, time: 4 },
        scene: { actor: 'worker', actorCount: 4, hideSkill: 'paint', hideHours: 2 },
      },
      {
        id: 'ustroit-soveshchanie',
        title: 'Устроить общее совещание',
        effect: 'После часа схем стороны соглашаются, что виноват чертёж.',
        note: 'Быстрое перемирие держится до следующей розетки.',
        deltas: { budget: -10, quality: -1, trust: -1, time: 2 },
        scene: { actor: 'worker', actorCount: 5, hideSkill: 'management', hideHours: 2, debris: 1 },
      },
    ],
  },
  {
    id: 'prorab-vne-seti',
    kicker: 'Управленческая пауза',
    title: 'Прораб ушёл в запой',
    text: 'Телефон прораба отвечает бодрым «абонент временно недоступен». Площадка тоже постепенно становится недоступной для управления.',
    minHour: 16,
    weight: 5,
    options: [
      {
        id: 'zamena-proraba',
        title: 'Прислать трезвую замену',
        effect: 'Новый прораб входит решительно и первым делом переименовывает все чаты.',
        note: 'Дорогая передача дел, зато работы снова кто-то координирует.',
        deltas: { budget: -140, quality: 2, trust: 3, time: 3 },
        scene: { actor: 'worker', actorCount: 1, hideSkill: 'management', hideHours: 3 },
      },
      {
        id: 'rukovodit-samomu',
        title: 'Руководить самому',
        effect: 'Вы узнаёте, что у пяти бригад одновременно был обещан один грузовой лифт.',
        note: 'Экономия на замене оплачивается вашим временем и качеством решений.',
        deltas: { budget: -15, quality: -3, trust: -2, time: 6 },
        scene: { hideSkill: 'management', hideHours: 6, debris: 2 },
      },
    ],
  },
  {
    id: 'lestnica-pobedila',
    kicker: 'Охрана труда',
    title: 'Рабочий подвернул ногу на стремянке',
    text: 'Травма лёгкая, но стремянка уже назначена главным подозреваемым и изолирована сигнальной лентой.',
    minHour: 7,
    weight: 7,
    options: [
      {
        id: 'vrach-i-akt',
        title: 'Вызвать медика и оформить акт',
        effect: 'Медик помогает рабочему, а инженер по охране труда — всем остальным почувствовать серьёзность момента.',
        note: 'Правильная процедура стоит времени, но укрепляет доверие.',
        deltas: { budget: -60, quality: 1, trust: 5, time: 3 },
        scene: { actor: 'medic', actorCount: 2, hideSkill: 'electric', hideHours: 4 },
      },
      {
        id: 'otpravit-na-taksi',
        title: 'Отправить в травмпункт на такси',
        effect: 'Коллеги провожают пострадавшего и сразу начинают спорить, кому достанется его перфоратор.',
        note: 'Быстрее, но небрежность процедуры заметит заказчик.',
        deltas: { budget: -30, quality: -1, trust: -3, time: 2 },
        scene: { actor: 'medic', actorCount: 1, hideSkill: 'electric', hideHours: 6 },
      },
    ],
  },
  {
    id: 'kraska-s-harakterom',
    kicker: 'Свежий воздух',
    title: 'Малярам стало нехорошо от запаха',
    text: 'Поставка оказалась особенно ароматной. Даже технический заказчик впервые читает паспорт безопасности до конца.',
    minHour: 11,
    weight: 6,
    options: [
      {
        id: 'provetrivanie-i-medik',
        title: 'Остановить покраску и проветрить',
        effect: 'Медик проверяет людей, вентиляция изображает промышленную мощь.',
        note: 'Безопасно и качественно, но стены подождут.',
        deltas: { budget: -45, quality: 3, trust: 4, time: 5 },
        scene: { actor: 'medic', actorCount: 1, hideSkill: 'paint', hideHours: 5, lightPower: 0.9 },
      },
      {
        id: 'smenit-material',
        title: 'Срочно сменить материал',
        effect: 'Новая краска безопаснее, дороже и на полтона «более корпоративная».',
        note: 'Работы продолжатся быстро, но смета и оттенок изменятся.',
        deltas: { budget: -120, quality: 1, trust: 1, time: 2 },
        scene: { actor: 'worker', actorCount: 2, hideSkill: 'paint', hideHours: 2, wallColor: '#c8d4dc' },
      },
    ],
  },
  {
    id: 'elektrik-na-bolnichnom',
    kicker: 'Ток событий',
    title: 'Единственный электрик взял больничный',
    text: 'Он прислал фотографию градусника. Прораб прислал фотографию тёмной переговорной. Обе выглядят убедительно.',
    minHour: 14,
    weight: 8,
    options: [
      {
        id: 'pozvat-subpodryad',
        title: 'Позвать аварийный субподряд',
        effect: 'Новый электрик приезжает с чемоданом приборов и тарифом как у кардиолога.',
        note: 'Свет возвращается быстро, бюджет слегка темнеет.',
        deltas: { budget: -150, quality: 2, trust: 2, time: 2 },
        scene: { actor: 'worker', actorCount: 1, hideSkill: 'electric', hideHours: 2, lightPower: 1 },
      },
      {
        id: 'sdvinut-raboty',
        title: 'Сдвинуть электрику',
        effect: 'Мебельщики начинают работать вокруг несуществующих розеток, как вокруг объектов культурного наследия.',
        note: 'Деньги сохранены, но очередность работ теряет достоинство.',
        deltas: { budget: 0, quality: -3, trust: -3, time: 6 },
        scene: { hideSkill: 'electric', hideHours: 6, lightPower: 0.35 },
      },
    ],
  },
  {
    id: 'nachalstvo-zabralo-lyudey',
    kicker: 'Корпоративная синергия',
    title: 'Начальство отдало вашу бригаду важному проекту',
    text: 'Важным оказался офис на два этажа выше. Ваш проект официально тоже важный, но другим шрифтом.',
    minHour: 20,
    weight: 7,
    options: [
      {
        id: 'torgovatsya-za-polovinu',
        title: 'Выторговать половину смены',
        effect: 'Рабочие курсируют между этажами и учатся красить в лифте взглядом.',
        note: 'Часть темпа сохранена, но раздробленная смена снижает качество.',
        deltas: { budget: -40, quality: -2, trust: 0, time: 4 },
        scene: { actor: 'worker', actorCount: 2, hideSkill: 'paint', hideHours: 4 },
      },
      {
        id: 'nanyat-vneshnih',
        title: 'Нанять внешних',
        effect: 'Внешняя бригада прибывает быстро и просит ещё раз показать, где у вас внешний угол.',
        note: 'Сроки защищены дорогой мобилизацией.',
        deltas: { budget: -190, quality: 0, trust: 3, time: 1 },
        scene: { actor: 'worker', actorCount: 4 },
      },
    ],
  },
  {
    id: 'subpodryadchik-podmenilsya',
    kicker: 'Глубина делегирования',
    title: 'Субподрядчик привёл своего субподрядчика',
    text: 'Тот, в свою очередь, привёл ещё одного. На четвёртом уровне никто уже не знает название проекта, но все выставляют счета.',
    minHour: 15,
    weight: 8,
    options: [
      {
        id: 'razobrat-cepochku',
        title: 'Разобрать цепочку договоров',
        effect: 'Менеджер рисует схему, похожую на семейное древо очень предприимчивой семьи.',
        note: 'Пауза возвращает контроль и качество.',
        deltas: { budget: -35, quality: 4, trust: 3, time: 4 },
        scene: { actor: 'inspector', actorCount: 1, hideSkill: 'management', hideHours: 4 },
      },
      {
        id: 'ostavit-kak-est',
        title: 'Пусть работают',
        effect: 'Работы идут бодро, а ответственность перемещается быстрее любой бригады.',
        note: 'Короткий выигрыш во времени с риском переделок.',
        deltas: { budget: -20, quality: -5, trust: -4, time: -2 },
        scene: { actor: 'worker', actorCount: 5, debris: 3 },
      },
    ],
  },
  {
    id: 'brigada-obyavila-ultimatum',
    kicker: 'Переговорная позиция',
    title: 'Бригада требует закрыть старые допработы',
    text: 'Рабочие сложили инструмент в идеальную линию. Такой порядок на площадке обычно означает, что сейчас станет дорого.',
    minHour: 17,
    weight: 7,
    options: [
      {
        id: 'zaplatit-chast',
        title: 'Закрыть согласованную часть',
        effect: 'После перевода инструмент мгновенно теряет выставочную симметрию и возвращается к работе.',
        note: 'Бюджет снижается, доверие и темп восстанавливаются.',
        deltas: { budget: -170, quality: 1, trust: 4, time: 1 },
        scene: { actor: 'worker', actorCount: 4 },
      },
      {
        id: 'otlozhit-do-aktov',
        title: 'Ждать подписанных актов',
        effect: 'Бригада ждёт вместе с вами, только сидя и значительно убедительнее.',
        note: 'Формально верно, практически медленно.',
        deltas: { budget: 0, quality: -1, trust: -5, time: 7 },
        scene: { actor: 'worker', actorCount: 4, hideSkill: 'moving', hideHours: 7 },
      },
    ],
  },
  {
    id: 'instrumentalnaya-zabastovka',
    kicker: 'Материальная ответственность',
    title: 'Инструмент оказался общим только на словах',
    text: 'Две бригады одновременно претендуют на один лазерный уровень. Сам уровень сохраняет нейтралитет.',
    minHour: 10,
    weight: 8,
    options: [
      {
        id: 'kupit-vtoroy',
        title: 'Купить второй комплект',
        effect: 'На площадке появляются два уровня и сразу две независимые версии горизонта.',
        note: 'Дороже, но конфликт и простой прекращаются.',
        deltas: { budget: -85, quality: 2, trust: 2, time: 1 },
        scene: { actor: 'worker', actorCount: 4 },
      },
      {
        id: 'vvesti-raspisanie',
        title: 'Ввести расписание выдачи',
        effect: 'Лазерный уровень получает календарь, личный номер и больше уважения, чем прораб.',
        note: 'Экономно, но смены начинают ждать свою очередь.',
        deltas: { budget: -10, quality: 0, trust: 0, time: 4 },
        scene: { hideSkill: 'furniture', hideHours: 4 },
      },
    ],
  },
  {
    id: 'dopusk-zastryal',
    kicker: 'Пропускной режим',
    title: 'Охрана не пускает новую бригаду',
    text: 'Список есть у прораба, прораб есть в чате, а чат у охраны официальным документом пока не признан.',
    minHour: 5,
    weight: 9,
    options: [
      {
        id: 'oformit-razovye',
        title: 'Оформить разовые пропуска',
        effect: 'Рабочие по одному проходят бюрократический квест у стойки охраны.',
        note: 'Небольшая задержка и чистая процедура.',
        deltas: { budget: -20, quality: 0, trust: 2, time: 3 },
        scene: { actor: 'inspector', actorCount: 1, hideSkill: 'moving', hideHours: 3 },
      },
      {
        id: 'peredat-rabotu-staroy-brigade',
        title: 'Передать работу тем, кто внутри',
        effect: 'Маляры берутся двигать шкафы и открывают в себе новые, не вполне безопасные компетенции.',
        note: 'Быстро, но специализация становится рекомендацией.',
        deltas: { budget: -30, quality: -4, trust: -2, time: 1 },
        scene: { actor: 'worker', actorCount: 3, debris: 2 },
      },
    ],
  },
  {
    id: 'prorab-prosit-avans',
    kicker: 'Мотивационная архитектура',
    title: 'Прораб просит аванс для удержания людей',
    text: 'По его словам, без аванса бригада уйдёт завтра. По бухгалтерии, с авансом она может уйти уже сегодня, но счастливой.',
    minHour: 13,
    weight: 7,
    options: [
      {
        id: 'avans-pod-vedomost',
        title: 'Дать аванс под ведомость',
        effect: 'Настроение бригады улучшается синхронно с появлением подписей.',
        note: 'Контролируемая выплата удерживает людей.',
        deltas: { budget: -120, quality: 1, trust: 3, time: 0 },
        scene: { actor: 'worker', actorCount: 4 },
      },
      {
        id: 'otkazat-do-etapa',
        title: 'Отказать до закрытия этапа',
        effect: 'Прораб принимает решение профессионально и начинает очень медленно листать календарь.',
        note: 'Деньги сохранены, мотивация и темп — не совсем.',
        deltas: { budget: 0, quality: -2, trust: -4, time: 5 },
        scene: { actor: 'worker', actorCount: 2, hideSkill: 'management', hideHours: 5 },
      },
    ],
  },
  {
    id: 'uborshchiki-otkazalis',
    kicker: 'Чистовой конфликт',
    title: 'Клининг отказался убирать за строителями',
    text: 'Строители уверены, что мусор почти декоративный. Клининг уверен, что слово «почти» отсутствует в договоре.',
    minHour: 19,
    weight: 7,
    options: [
      {
        id: 'zakazat-stroitelnuyu-uborku',
        title: 'Заказать строительную уборку',
        effect: 'Приезжает отдельная команда с промышленным пылесосом и взглядом людей, видевших всё.',
        note: 'Дорого, зато площадка снова похожа на офис.',
        deltas: { budget: -110, quality: 4, trust: 3, time: 2 },
        scene: { actor: 'worker', actorCount: 3, hideSkill: 'cleaning', hideHours: 2, debris: -5 },
      },
      {
        id: 'ubirat-silami-brigad',
        title: 'Заставить бригады убрать',
        effect: 'Каждая бригада аккуратно переносит свой мусор в зону ответственности соседей.',
        note: 'Экономия превращается в управленческую археологию.',
        deltas: { budget: -15, quality: -2, trust: -3, time: 5 },
        scene: { actor: 'worker', actorCount: 4, hideSkill: 'cleaning', hideHours: 5, debris: 1 },
      },
    ],
  },
  {
    id: 'montazhnik-zastryal-v-lifte',
    kicker: 'Вертикальная логистика',
    title: 'Монтажник застрял в грузовом лифте',
    text: 'Он цел, спокоен и уже руководит разгрузкой по телефону. Лифт тем временем объявил личный технический перерыв.',
    minHour: 8,
    weight: 6,
    options: [
      {
        id: 'vyzvat-avariynuyu',
        title: 'Вызвать аварийную службу',
        effect: 'Специалисты освобождают монтажника и выдают лифту строгую устную рекомендацию.',
        note: 'Безопасное решение с коротким простоем.',
        deltas: { budget: -50, quality: 1, trust: 4, time: 3 },
        scene: { actor: 'medic', actorCount: 1, hideSkill: 'moving', hideHours: 3 },
      },
      {
        id: 'pustit-po-lestnice',
        title: 'Носить материалы по лестнице',
        effect: 'Бригада считает ступени, этажи и новые основания для доплаты.',
        note: 'Работа продолжается, но медленнее и дороже для людей.',
        deltas: { budget: -75, quality: -1, trust: -1, time: 4 },
        scene: { actor: 'worker', actorCount: 4, hideSkill: 'moving', hideHours: 2, debris: 1 },
      },
    ],
  },
];
